# Generated by Django 5.2.17 on 2026-09-13 20:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("credentials", "0004_credentialservice_org_scoping"),
        ("organizations", "0001_initial"),
        ("runners", "0015_workspaceprocess_name_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the plugin definition is enabled (staff switch).",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the plugin is visible for org/workspace activation.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_plugins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for global OpenCuria plugins; set for org-owned plugins.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugins",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "plugins_plugin",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrgPluginActivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_plugin_activations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_activations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_activations",
                        to="plugins.plugin",
                    ),
                ),
            ],
            options={
                "db_table": "plugins_org_activation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PluginCredentialRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable requirement identifier within the plugin.",
                        max_length=255,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "plugin_owned_service",
                    models.BooleanField(
                        default=False,
                        help_text="True when the referenced service was created exclusively for this plugin via the plugin API.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credential_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plugin_requirements",
                        to="credentials.credentialservice",
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential_requirements",
                        to="plugins.plugin",
                    ),
                ),
            ],
            options={
                "db_table": "plugins_credential_requirement",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="PluginMcpServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("stdio", "STDIO"),
                            ("streamable_http", "Streamable HTTP"),
                            ("sse", "SSE"),
                        ],
                        default="stdio",
                        max_length=20,
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Single executable for stdio transport (no shell).",
                        max_length=1024,
                    ),
                ),
                (
                    "args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Argument list (never joined into a shell string).",
                    ),
                ),
                (
                    "cwd",
                    models.CharField(blank=True, default="/workspace", max_length=1024),
                ),
                (
                    "env",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Env mapping; values may use {{credential.KEY}} placeholders.",
                    ),
                ),
                ("url", models.CharField(blank=True, default="", max_length=2048)),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Header mapping; values may use {{credential.KEY}} placeholders.",
                    ),
                ),
                ("startup_timeout_seconds", models.PositiveIntegerField(default=30)),
                ("request_timeout_seconds", models.PositiveIntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_servers",
                        to="plugins.plugin",
                    ),
                ),
            ],
            options={
                "db_table": "plugins_mcp_server",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PluginSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "body",
                    models.TextField(
                        help_text="Markdown content appended to the prompt."
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_skills",
                        to="plugins.plugin",
                    ),
                ),
            ],
            options={
                "db_table": "plugins_skill",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkspacePluginActivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_plugin_activations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_activations",
                        to="plugins.plugin",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_activations",
                        to="runners.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "plugins_workspace_activation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="plugin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", True)),
                fields=("slug",),
                name="unique_global_plugin_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="plugin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("organization", "slug"),
                name="unique_org_plugin_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgpluginactivation",
            constraint=models.UniqueConstraint(
                fields=("organization", "plugin"), name="unique_org_plugin_activation"
            ),
        ),
        migrations.AddConstraint(
            model_name="plugincredentialrequirement",
            constraint=models.UniqueConstraint(
                fields=("plugin", "key"),
                name="unique_plugin_credential_requirement_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="plugincredentialrequirement",
            constraint=models.UniqueConstraint(
                fields=("plugin", "credential_service"),
                name="unique_plugin_credential_requirement_service",
            ),
        ),
        migrations.AddConstraint(
            model_name="pluginmcpserver",
            constraint=models.UniqueConstraint(
                fields=("plugin", "slug"), name="unique_plugin_mcp_server_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="pluginskill",
            constraint=models.UniqueConstraint(
                fields=("plugin", "slug"), name="unique_plugin_skill_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacepluginactivation",
            constraint=models.UniqueConstraint(
                fields=("workspace", "plugin"),
                name="unique_workspace_plugin_activation",
            ),
        ),
    ]
