# Generated by OpenCuria on 2026-09-13

"""Seed the global Playwright plugin (idempotent, explicit opt-in only)."""

from __future__ import annotations

import uuid

from django.db import migrations

PLAYWRIGHT_PLUGIN_ID = uuid.UUID("b1a7c2e4-9f3d-4a5b-8c6d-7e8f9a0b1c2d")
PLAYWRIGHT_PLUGIN_SLUG = "playwright"

PLAYWRIGHT_MCP_ARGS = [
    "-y",
    "@playwright/mcp@latest",
    "--headless",
    "--isolated",
    "--no-sandbox",
    "--executable-path",
    "/usr/bin/google-chrome-stable",
    "--output-dir",
    "/workspace/.opencuria/playwright",
]

PLAYWRIGHT_SKILL_BODY = """\
# Playwright Browser Automation

Use the Playwright MCP server to drive a headless Chromium browser for
end-to-end testing and web inspection.

- Prefer isolated browser contexts for reproducible runs.
- Take screenshots or snapshots to verify page state before acting.
- Keep selectors stable (roles, labels, test ids) instead of fragile XPaths.
- Store test artifacts under /workspace/.opencuria/playwright.
"""


def seed_playwright_plugin(apps, schema_editor):
    plugin_model = apps.get_model("plugins", "Plugin")
    skill_model = apps.get_model("plugins", "PluginSkill")
    mcp_model = apps.get_model("plugins", "PluginMcpServer")

    plugin = (
        plugin_model.objects.filter(id=PLAYWRIGHT_PLUGIN_ID).first()
        or plugin_model.objects.filter(
            slug=PLAYWRIGHT_PLUGIN_SLUG, organization__isnull=True
        ).first()
    )
    if plugin is None:
        plugin = plugin_model.objects.create(
            id=PLAYWRIGHT_PLUGIN_ID,
            organization=None,
            name="Playwright",
            slug=PLAYWRIGHT_PLUGIN_SLUG,
            description=(
                "Global browser automation plugin backed by the Playwright MCP "
                "server (headless Chromium). Activate it explicitly per "
                "organization to use it in workspaces."
            ),
            enabled=True,
            published=True,
        )
    else:
        plugin.organization = None
        plugin.name = "Playwright"
        plugin.slug = PLAYWRIGHT_PLUGIN_SLUG
        plugin.description = (
            "Global browser automation plugin backed by the Playwright MCP "
            "server (headless Chromium). Activate it explicitly per "
            "organization to use it in workspaces."
        )
        plugin.enabled = True
        plugin.published = True
        plugin.save()

    skill_model.objects.update_or_create(
        plugin=plugin,
        slug="playwright-basics",
        defaults={
            "name": "Playwright Basics",
            "body": PLAYWRIGHT_SKILL_BODY,
            "position": 0,
        },
    )

    mcp_model.objects.update_or_create(
        plugin=plugin,
        slug="playwright",
        defaults={
            "name": "Playwright",
            "transport": "stdio",
            "command": "npx",
            "args": PLAYWRIGHT_MCP_ARGS,
            "cwd": "/workspace",
            "env": {},
            "url": "",
            "headers": {},
            "startup_timeout_seconds": 30,
            "request_timeout_seconds": 60,
        },
    )
    # Explicit opt-in: never create OrgPluginActivation rows here.


def unseed_playwright_plugin(apps, schema_editor):
    plugin_model = apps.get_model("plugins", "Plugin")
    plugin_model.objects.filter(id=PLAYWRIGHT_PLUGIN_ID).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            seed_playwright_plugin,
            unseed_playwright_plugin,
        ),
    ]
