# Generated by OpenCuria on 2026-09-14

"""Harden the Playwright plugin seed for root-owned QEMU workspaces.

The base VM image ships ``/workspace`` owned by root while the SSH user
is ``ubuntu`` (passwordless sudo). The previous seed pointed the MCP
``--output-dir`` at ``/workspace/.opencuria/playwright``, which the
server cannot create there. Point it at a user-writable path and give
the slow first ``npx`` download more startup budget.
"""

from __future__ import annotations

from django.db import migrations

PLAYWRIGHT_PLUGIN_ID_STR = "b1a7c2e4-9f3d-4a5b-8c6d-7e8f9a0b1c2d"
PLAYWRIGHT_PLUGIN_SLUG_STR = "playwright"

PLAYWRIGHT_MCP_ARGS_V2 = [
    "-y",
    "@playwright/mcp@latest",
    "--headless",
    "--isolated",
    "--no-sandbox",
    "--executable-path",
    "/usr/bin/google-chrome-stable",
    "--output-dir",
    "/tmp/.opencuria/playwright",
]

PLAYWRIGHT_MCP_ARGS_V1 = [
    "-y",
    "@playwright/mcp@latest",
    "--headless",
    "--isolated",
    "--no-sandbox",
    "--executable-path",
    "/usr/bin/google-chrome-stable",
    "--output-dir",
    "/workspace/.opencuria/playwright",
]


def harden_playwright_seed(apps, schema_editor):
    import uuid

    plugin_model = apps.get_model("plugins", "Plugin")
    mcp_model = apps.get_model("plugins", "PluginMcpServer")
    plugin = (
        plugin_model.objects.filter(id=uuid.UUID(PLAYWRIGHT_PLUGIN_ID_STR)).first()
        or plugin_model.objects.filter(
            slug=PLAYWRIGHT_PLUGIN_SLUG_STR, organization__isnull=True
        ).first()
    )
    if plugin is None:
        return
    mcp_model.objects.filter(plugin=plugin, slug="playwright").update(
        args=PLAYWRIGHT_MCP_ARGS_V2,
        startup_timeout_seconds=120,
    )


def restore_playwright_seed(apps, schema_editor):
    import uuid

    plugin_model = apps.get_model("plugins", "Plugin")
    mcp_model = apps.get_model("plugins", "PluginMcpServer")
    plugin = (
        plugin_model.objects.filter(id=uuid.UUID(PLAYWRIGHT_PLUGIN_ID_STR)).first()
        or plugin_model.objects.filter(
            slug=PLAYWRIGHT_PLUGIN_SLUG_STR, organization__isnull=True
        ).first()
    )
    if plugin is None:
        return
    mcp_model.objects.filter(plugin=plugin, slug="playwright").update(
        args=PLAYWRIGHT_MCP_ARGS_V1,
        startup_timeout_seconds=30,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0002_seed_playwright_plugin"),
    ]

    operations = [
        migrations.RunPython(
            harden_playwright_seed,
            restore_playwright_seed,
        ),
    ]
