# Generated by OpenCuria on 2026-09-18

"""Run Playwright MCP headed on the shared workspace desktop (:1).

The seed starts headless Chromium (invisible in the desktop viewer).
Switch to headed with ``DISPLAY``/``XAUTHORITY`` on the shared KasmVNC
display so the browser window is live in the viewer; ``--headless`` is
dropped (headed is the playwright-mcp default and needs a display).
"""

from __future__ import annotations

from django.db import migrations

PLAYWRIGHT_PLUGIN_ID_STR = "b1a7c2e4-9f3d-4a5b-8c6d-7e8f9a0b1c2d"
PLAYWRIGHT_PLUGIN_SLUG_STR = "playwright"

PLAYWRIGHT_MCP_ARGS_V3 = [
    "-y",
    "@playwright/mcp@latest",
    "--isolated",
    "--no-sandbox",
    "--executable-path",
    "/usr/bin/google-chrome-stable",
    "--output-dir",
    "/tmp/.opencuria/playwright",
]

PLAYWRIGHT_MCP_ENV_V3 = {
    "DISPLAY": ":1",
    "XAUTHORITY": "/root/.Xauthority",
}

PLAYWRIGHT_MCP_ARGS_V2 = [
    "-y",
    "@playwright/mcp@latest",
    "--headless",
    "--isolated",
    "--no-sandbox",
    "--executable-path",
    "/usr/bin/google-chrome-stable",
    "--output-dir",
    "/tmp/.opencuria/playwright",
]


def show_playwright_on_desktop(apps, schema_editor):
    import uuid

    plugin_model = apps.get_model("plugins", "Plugin")
    mcp_model = apps.get_model("plugins", "PluginMcpServer")
    plugin = (
        plugin_model.objects.filter(id=uuid.UUID(PLAYWRIGHT_PLUGIN_ID_STR)).first()
        or plugin_model.objects.filter(
            slug=PLAYWRIGHT_PLUGIN_SLUG_STR, organization__isnull=True
        ).first()
    )
    if plugin is None:
        return
    mcp_model.objects.filter(plugin=plugin, slug="playwright").update(
        args=PLAYWRIGHT_MCP_ARGS_V3,
        env=PLAYWRIGHT_MCP_ENV_V3,
    )


def hide_playwright_headless(apps, schema_editor):
    import uuid

    plugin_model = apps.get_model("plugins", "Plugin")
    mcp_model = apps.get_model("plugins", "PluginMcpServer")
    plugin = (
        plugin_model.objects.filter(id=uuid.UUID(PLAYWRIGHT_PLUGIN_ID_STR)).first()
        or plugin_model.objects.filter(
            slug=PLAYWRIGHT_PLUGIN_SLUG_STR, organization__isnull=True
        ).first()
    )
    if plugin is None:
        return
    mcp_model.objects.filter(plugin=plugin, slug="playwright").update(
        args=PLAYWRIGHT_MCP_ARGS_V2,
        env={},
    )


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0003_playwright_seed_hardening"),
    ]

    operations = [
        migrations.RunPython(
            show_playwright_on_desktop,
            hide_playwright_headless,
        ),
    ]
