# Generated by Django 5.2.17 on 2026-10-01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plugins", "0007_repair_notion_mcp_oauth"),
        ("credentials", "0008_plugin_credential_separation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plugincredentialrequirement",
            name="plugin_owned_service",
        ),
    ]
