# Generated by Django 5.2.13 on 2026-09-05 09:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_encrypted', models.TextField(help_text='Fernet-encrypted provider API key.')),
                ('base_url', models.URLField(default='https://openrouter.ai/api/v1', help_text='OpenAI-compatible API base URL.', max_length=1024)),
                ('default_model', models.CharField(blank=True, default='', help_text='Default model for agentic runs.', max_length=255)),
                ('small_model', models.CharField(blank=True, default='', help_text='Cheaper model for title/compaction tasks.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(help_text='Owning organization (exactly one config per org).', on_delete=django.db.models.deletion.CASCADE, related_name='harness_provider_config', to='organizations.organization')),
            ],
            options={
                'db_table': 'harness_provider_config',
                'ordering': ['-updated_at'],
            },
        ),
    ]
