# Generated by Django 5.2.13 on 2026-09-05 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0002_permissions'),
        ('runners', '0010_imagedefinition_delete_attempt_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarnessMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField(blank=True, default='')),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('cost', models.FloatField(default=0.0)),
                ('tokens', models.JSONField(blank=True, default=dict, help_text='Usage for this message {prompt, completion, total}.')),
                ('finish', models.CharField(blank=True, default='', max_length=32)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'harness_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HarnessPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('reasoning', 'Reasoning'), ('tool', 'Tool'), ('step-start', 'Step start'), ('step-finish', 'Step finish'), ('subtask', 'Subtask'), ('patch', 'Patch'), ('agent', 'Agent')], max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=16)),
                ('call_id', models.CharField(blank=True, default='', max_length=255)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Extra payload (step number, cost, tokens, subtask id).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='harness.harnessmessage')),
            ],
            options={
                'db_table': 'harness_part',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HarnessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(help_text='Owning organization for scoping (mirrors workspace org).')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('mode', models.CharField(choices=[('plan', 'Plan'), ('build', 'Build')], default='build', max_length=16)),
                ('agent_name', models.CharField(default='build', max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('busy', 'Busy'), ('idle', 'Idle')], default='idle', max_length=16)),
                ('cost', models.FloatField(default=0.0)),
                ('tokens', models.JSONField(blank=True, default=dict, help_text='Aggregated token usage {prompt, completion, total}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent session for subagent runs (null for top-level).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='harness.harnesssession')),
                ('workspace', models.ForeignKey(help_text='Workspace this session runs in.', on_delete=django.db.models.deletion.CASCADE, related_name='harness_sessions', to='runners.workspace')),
            ],
            options={
                'db_table': 'harness_session',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='harnessmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='harness.harnesssession'),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('priority', models.CharField(blank=True, default='medium', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='harness.harnesssession')),
            ],
            options={
                'db_table': 'harness_todo',
                'ordering': ['session', 'order', 'created_at'],
            },
        ),
    ]
