# Generated by Django 5.2.17 on 2026-09-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0014_remove_providerconfig_legacy_openrouter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerconfig',
            name='computer_use_effort',
            field=models.CharField(blank=True, default='', help_text='Default reasoning effort for computer-use model.', max_length=50),
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='default_effort',
            field=models.CharField(blank=True, default='', help_text='Default reasoning effort for default model.', max_length=50),
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='small_effort',
            field=models.CharField(blank=True, default='', help_text='Default reasoning effort for small model.', max_length=50),
        ),
    ]
