# Generated by Django 5.2.17 on 2026-09-11 22:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


def _forward(apps, schema_editor):
    AgentSConfig = apps.get_model("harness", "AgentSConfig")
    Organization = apps.get_model("organizations", "Organization")
    for org in Organization.objects.all().iterator():
        AgentSConfig.objects.get_or_create(
            organization_id=org.id,
            defaults={
                "grounding_model": "",
                "grounding_width": 1920,
                "grounding_height": 1080,
                "model_temperature": None,
                "max_steps": 15,
                "max_trajectory_length": 8,
                "enable_reflection": True,
                "enable_code_agent": True,
                "screenshot_max_dimension": 2400,
                "action_pre_delay": 1.0,
                "action_post_delay": 1.0,
                "wait_delay": 5.0,
            },
        )


def _reverse(apps, schema_editor):
    AgentSConfig = apps.get_model("harness", "AgentSConfig")
    AgentSConfig.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0016_agentconfig"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerconnection",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openrouter", "OpenRouter"),
                    ("chatgpt", "ChatGPT"),
                    ("amazon-bedrock", "Amazon Bedrock"),
                    ("openai-compatible", "OpenAI Compatible"),
                ],
                help_text=(
                    "Provider identifier "
                    "(openrouter, chatgpt, amazon-bedrock, openai-compatible)."
                ),
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AgentSConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grounding_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=(
                            "Grounding model ref; "
                            "empty falls back to the run's main model."
                        ),
                        max_length=255,
                    ),
                ),
                ("grounding_width", models.PositiveIntegerField(default=1920)),
                ("grounding_height", models.PositiveIntegerField(default=1080)),
                (
                    "model_temperature",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("max_steps", models.IntegerField(default=15)),
                ("max_trajectory_length", models.IntegerField(default=8)),
                ("enable_reflection", models.BooleanField(default=True)),
                ("enable_code_agent", models.BooleanField(default=True)),
                ("screenshot_max_dimension", models.IntegerField(default=2400)),
                ("action_pre_delay", models.FloatField(default=1.0)),
                ("action_post_delay", models.FloatField(default=1.0)),
                ("wait_delay", models.FloatField(default=5.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        help_text="Owning organization (exactly one Agent-S config per org).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harness_agent_s_config",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "harness_agent_s_config",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RunPython(_forward, _reverse),
    ]
