# Generated by opencuria on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0017_agentsconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsconfig",
            name="enable_recording",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Opt-in session recording for computer-use runs (mp4, "
                    "org-wide, default off)."
                ),
            ),
        ),
    ]
