# Generated by Django 5.2.17 on 2026-09-15 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0019_agentsconfig_recording'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(help_text='Catalog model id (e.g. openrouter/provider/name).', max_length=255)),
                ('effort', models.CharField(blank=True, default='', help_text='Last-used reasoning effort for this model.', max_length=50)),
                ('last_used_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When the model was last used (drives Recent ordering).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(help_text='Owning organization (scoping).', on_delete=django.db.models.deletion.CASCADE, related_name='recent_models', to='organizations.organization')),
                ('user', models.ForeignKey(help_text='User who used the model.', on_delete=django.db.models.deletion.CASCADE, related_name='recent_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'harness_recent_model',
                'ordering': ['-last_used_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user', 'model'), name='harness_recent_model_org_user_model_uniq')],
            },
        ),
    ]
