# Generated by Django 5.2.17 on 2026-09-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0023_harness_message_part_positions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harnessmessage',
            options={'ordering': ['position', 'created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='harnesspart',
            options={'ordering': ['position', 'created_at', 'id']},
        ),
    ]
