# Generated by Django 5.2.17 on 2026-10-03 07:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0026_backfill_harnesspart_display"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubagentConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_depth", models.PositiveIntegerField(default=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harness_subagent_config",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "harness_subagent_config",
                "ordering": ["-updated_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_depth__gte", 1)),
                        name="harness_subagent_config_depth_gte_1",
                    )
                ],
            },
        ),
    ]
