# Generated by Django 5.2.12 on 2026-04-01 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('runners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Markdown content appended to the prompt.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skills', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Set for org-shared skills (mutually exclusive with user).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, help_text='Set for personal skills (mutually exclusive with organization).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skills_skill',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SessionSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Snapshot of skill name at time of use.', max_length=255)),
                ('body', models.TextField(help_text='Snapshot of skill body at time of use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_skills', to='runners.session')),
                ('skill', models.ForeignKey(blank=True, help_text='Nullable — preserved even if the source skill is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_skills', to='skills.skill')),
            ],
            options={
                'db_table': 'skills_session_skill',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('user__isnull', False)), models.Q(('organization__isnull', False), ('user__isnull', True)), _connector='OR'), name='skill_owner_exclusive'),
        ),
    ]
