# Generated by Django 5.2.13 on 2026-09-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionSkill',
        ),
    ]
