# Generated by Django 5.2.12 on 2026-04-01 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable service name (e.g. 'GitHub').", max_length=255)),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g. 'github').", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description shown to users.')),
                ('credential_type', models.CharField(choices=[('env', 'Environment Variable'), ('ssh_key', 'SSH Key')], default='env', help_text='How this credential is injected into a workspace.', max_length=20)),
                ('env_var_name', models.CharField(blank=True, default='', help_text="Name of the environment variable (e.g. 'GITHUB_TOKEN'). Only used when credential_type is 'env'.", max_length=255)),
                ('label', models.CharField(blank=True, default='', help_text="Short label shown to users (e.g. 'Personal Access Token').", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credentials_service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="User-chosen display name (e.g. 'My GitHub PAT').", max_length=255)),
                ('encrypted_value', models.TextField(help_text='Fernet-encrypted credential value.')),
                ('public_key', models.TextField(blank=True, default='', help_text='Public key in OpenSSH format (only for ssh_key type).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Set for org credentials (mutually exclusive with user).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, help_text='Set for personal credentials (mutually exclusive with organization).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_credentials', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='credentials.credentialservice')),
            ],
            options={
                'db_table': 'credentials_credential',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('user__isnull', False)), models.Q(('organization__isnull', False), ('user__isnull', True)), _connector='OR'), name='credential_owner_exclusive')],
            },
        ),
        migrations.CreateModel(
            name='OrgCredentialServiceActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_activations', to='credentials.credentialservice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_service_activations', to='organizations.organization')),
            ],
            options={
                'db_table': 'credentials_org_service_activation',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'credential_service'), name='unique_org_credential_service_activation')],
            },
        ),
    ]
