# Generated by Django 5.2.12 on 2026-04-02

import uuid

from django.db import migrations


SEED_CREDENTIAL_SERVICES = [
    {
        "id": "65dab691-e337-4eb8-9c4b-204c3e75a1fa",
        "name": "Claude OAuth Token",
        "slug": "claude-oauth-token",
        "description": "",
        "credential_type": "env",
        "env_var_name": "CLAUDE_CODE_OAUTH_TOKEN",
        "label": "OAuth Token",
    },
    {
        "id": "6375b64d-de0e-4876-af7b-b5433e3f6228",
        "name": "GitHub",
        "slug": "github",
        "description": "",
        "credential_type": "env",
        "env_var_name": "GITHUB_TOKEN",
        "label": "Personal Access Token",
    },
    {
        "id": "23eeffaf-663d-431f-b96a-029765ac48c3",
        "name": "OpenRouter",
        "slug": "openrouter",
        "description": "",
        "credential_type": "env",
        "env_var_name": "OPENROUTER_API_KEY",
        "label": "OpenRouter API Key",
    },
    {
        "id": "1de1b81b-fb20-497b-b17b-349e525dd927",
        "name": "SSH Key",
        "slug": "ssh-key",
        "description": "Ed25519 SSH key pair for Git and other SSH-based access.",
        "credential_type": "ssh_key",
        "env_var_name": "",
        "label": "SSH Key Pair",
    },
]


def seed_global_credential_services(apps, schema_editor):
    credential_service_model = apps.get_model("credentials", "CredentialService")
    organization_model = apps.get_model("organizations", "Organization")
    activation_model = apps.get_model("credentials", "OrgCredentialServiceActivation")
    seeded_services = []

    for seed in SEED_CREDENTIAL_SERVICES:
        service = (
            credential_service_model.objects.filter(id=seed["id"]).first()
            or credential_service_model.objects.filter(slug=seed["slug"]).first()
        )

        if service is None:
            service = credential_service_model.objects.create(
                id=uuid.UUID(seed["id"]),
                name=seed["name"],
                slug=seed["slug"],
                description=seed["description"],
                credential_type=seed["credential_type"],
                env_var_name=seed["env_var_name"],
                label=seed["label"],
            )
            seeded_services.append(service)
            continue

        service.name = seed["name"]
        service.slug = seed["slug"]
        service.description = seed["description"]
        service.credential_type = seed["credential_type"]
        service.env_var_name = seed["env_var_name"]
        service.label = seed["label"]
        service.save()
        seeded_services.append(service)

    organizations = list(organization_model.objects.all())
    activation_model.objects.bulk_create(
        [
            activation_model(organization=org, credential_service=service)
            for org in organizations
            for service in seeded_services
        ],
        ignore_conflicts=True,
    )


def unseed_global_credential_services(apps, schema_editor):
    credential_service_model = apps.get_model("credentials", "CredentialService")
    credential_service_model.objects.filter(
        id__in=[uuid.UUID(seed["id"]) for seed in SEED_CREDENTIAL_SERVICES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            seed_global_credential_services,
            unseed_global_credential_services,
        ),
    ]
