# Generated by Django 5.2.13 on 2026-04-17 17:38

import uuid

from django.db import migrations, models


CODEX_CREDENTIAL_SERVICE = {
    "id": "74fb7e0b-5f0f-4803-a489-4a39124ad24b",
    "name": "OpenAI Codex Auth",
    "slug": "openai-codex-auth",
    "description": "Auth file for the OpenAI Codex CLI.",
    "credential_type": "file",
    "env_var_name": "",
    "target_path": "~/.codex/auth.json",
    "label": "auth.json",
}


def seed_codex_credential_service(apps, schema_editor):
    credential_service_model = apps.get_model("credentials", "CredentialService")
    organization_model = apps.get_model("organizations", "Organization")
    activation_model = apps.get_model("credentials", "OrgCredentialServiceActivation")

    service = (
        credential_service_model.objects.filter(id=uuid.UUID(CODEX_CREDENTIAL_SERVICE["id"])).first()
        or credential_service_model.objects.filter(slug=CODEX_CREDENTIAL_SERVICE["slug"]).first()
    )

    if service is None:
        service = credential_service_model.objects.create(
            id=uuid.UUID(CODEX_CREDENTIAL_SERVICE["id"]),
            name=CODEX_CREDENTIAL_SERVICE["name"],
            slug=CODEX_CREDENTIAL_SERVICE["slug"],
            description=CODEX_CREDENTIAL_SERVICE["description"],
            credential_type=CODEX_CREDENTIAL_SERVICE["credential_type"],
            env_var_name=CODEX_CREDENTIAL_SERVICE["env_var_name"],
            target_path=CODEX_CREDENTIAL_SERVICE["target_path"],
            label=CODEX_CREDENTIAL_SERVICE["label"],
        )
    else:
        service.name = CODEX_CREDENTIAL_SERVICE["name"]
        service.slug = CODEX_CREDENTIAL_SERVICE["slug"]
        service.description = CODEX_CREDENTIAL_SERVICE["description"]
        service.credential_type = CODEX_CREDENTIAL_SERVICE["credential_type"]
        service.env_var_name = CODEX_CREDENTIAL_SERVICE["env_var_name"]
        service.target_path = CODEX_CREDENTIAL_SERVICE["target_path"]
        service.label = CODEX_CREDENTIAL_SERVICE["label"]
        service.save()

    activation_model.objects.bulk_create(
        [
            activation_model(
                organization=organization,
                credential_service=service,
            )
            for organization in organization_model.objects.all()
        ],
        ignore_conflicts=True,
    )


def unseed_codex_credential_service(apps, schema_editor):
    credential_service_model = apps.get_model("credentials", "CredentialService")
    credential_service_model.objects.filter(
        id=uuid.UUID(CODEX_CREDENTIAL_SERVICE["id"])
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_seed_global_credential_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialservice',
            name='target_path',
            field=models.CharField(blank=True, default='', help_text="Target file path inside the workspace (e.g. '~/.codex/auth.json'). Only used when credential_type is 'file'. Relative paths are resolved against the workspace HOME directory.", max_length=1024),
        ),
        migrations.AlterField(
            model_name='credentialservice',
            name='credential_type',
            field=models.CharField(choices=[('env', 'Environment Variable'), ('file', 'Credential File'), ('ssh_key', 'SSH Key')], default='env', help_text='How this credential is injected into a workspace.', max_length=20),
        ),
        migrations.RunPython(
            seed_codex_credential_service,
            unseed_codex_credential_service,
        ),
    ]
