# Generated by Django 5.2.17 on 2026-09-13 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0003_credentialservice_target_path_and_more"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialservice",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for global services; set for org-owned services (e.g. created for a plugin).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credential_services",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="credentialservice",
            name="slug",
            field=models.SlugField(
                help_text="URL-safe identifier (e.g. 'github').", max_length=255
            ),
        ),
        migrations.AddConstraint(
            model_name="credentialservice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", True)),
                fields=("slug",),
                name="unique_global_credential_service_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="credentialservice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("organization", "slug"),
                name="unique_org_credential_service_slug",
            ),
        ),
    ]
