# Generated by Django 5.2.17; this migration also safely rewrites legacy grants.

import hashlib
import json
import uuid
from urllib.parse import urlsplit

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

_NAMESPACE = uuid.UUID("d36753cc-120d-42fe-a6d8-510b8c7f24e4")


def _safe_endpoint(value):
    if (
        not isinstance(value, str)
        or not value
        or any(ord(char) < 0x21 for char in value)
    ):
        return False
    try:
        parsed = urlsplit(value)
        port = parsed.port
    except ValueError:
        return False
    return bool(
        parsed.scheme == "https"
        and parsed.hostname
        and parsed.netloc
        and not parsed.username
        and not parsed.password
        and "@" not in parsed.netloc
        and not parsed.query
        and not parsed.fragment
        and "?" not in value
        and "#" not in value
        and (port is None or 1 <= port <= 65535)
    )


def _resource_matches(server_url, resource):
    """Accept only public HTTPS resource identifiers scoped to the MCP endpoint."""
    if not _safe_endpoint(server_url) or not _safe_endpoint(resource):
        return False
    server, candidate = urlsplit(server_url), urlsplit(resource)
    try:
        if server.hostname.lower() != candidate.hostname.lower() or (
            server.port or 443
        ) != (candidate.port or 443):
            return False
    except (AttributeError, ValueError):
        return False
    server_path = (server.path or "/").rstrip("/") or "/"
    resource_path = (candidate.path or "/").rstrip("/") or "/"
    return server_path == resource_path or server_path.startswith(
        resource_path.rstrip("/") + "/"
    )


def flush_deferred_constraints(apps, schema_editor):
    """Finish PostgreSQL FK trigger events before the migration's DDL phase."""
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def separate_legacy_oauth(apps, schema_editor):
    """Route legacy grants only through their exact original service graph."""
    from common.utils import decrypt_value, encrypt_value

    Service = apps.get_model("credentials", "CredentialService")
    Credential = apps.get_model("credentials", "Credential")
    Registration = apps.get_model("credentials", "McpOAuthClientRegistration")
    State = apps.get_model("credentials", "McpOAuthAuthorizationState")
    Requirement = apps.get_model("plugins", "PluginCredentialRequirement")
    Server = apps.get_model("plugins", "PluginMcpServer")
    Plugin = apps.get_model("plugins", "Plugin")
    Membership = apps.get_model("organizations", "Membership")
    Activation = apps.get_model("credentials", "OrgCredentialServiceActivation")
    Organization = apps.get_model("organizations", "Organization")

    services = {row.id: row for row in Service.objects.all()}
    plugins = {row.id: row for row in Plugin.objects.all()}
    servers = {row.id: row for row in Server.objects.filter(auth_type="oauth")}
    requirements = list(
        Requirement.objects.filter(credential_service__credential_type="mcp_oauth")
        .select_related("plugin")
        .order_by("id")
    )
    requirements_by_service = {}
    old_edges = {}
    servers_by_requirement = {}
    for server in servers.values():
        servers_by_requirement.setdefault(
            (server.plugin_id, server.oauth_requirement_key), []
        ).append(server)
    for req in requirements:
        requirements_by_service.setdefault(req.credential_service_id, []).append(req)
        old_edges[req.id] = {
            "service_id": req.credential_service_id,
            "plugin_id": req.plugin_id,
            "key": req.key,
            "required": req.required,
            "servers": [
                server
                for server in servers_by_requirement.get((req.plugin_id, req.key), [])
                if req.required and _safe_endpoint(server.url)
            ],
        }

    def service_visible(service, credential) -> bool:
        if credential.user_id is not None:
            return credential.organization_id is None and (
                service.organization_id is None
                or Membership.objects.filter(
                    user_id=credential.user_id,
                    organization_id=service.organization_id,
                ).exists()
            )
        return credential.organization_id is not None and service.organization_id in {
            None,
            credential.organization_id,
        }

    def plugin_visible(plugin, credential) -> bool:
        if plugin is None:
            return False
        if credential.organization_id is not None:
            return plugin.organization_id in {None, credential.organization_id}
        return credential.user_id is not None and (
            plugin.organization_id is None
            or Membership.objects.filter(
                user_id=credential.user_id,
                organization_id=plugin.organization_id,
            ).exists()
        )

    def safe_registration(registration, endpoint: str, resource: str) -> bool:
        return bool(
            registration
            and registration.server_url == endpoint
            and _safe_endpoint(registration.issuer)
            and _safe_endpoint(registration.authorization_endpoint)
            and _safe_endpoint(registration.token_endpoint)
            and (
                not registration.registration_endpoint
                or _safe_endpoint(registration.registration_endpoint)
            )
            and isinstance(registration.client_id, str)
            and registration.client_id
            and _resource_matches(endpoint, resource)
        )

    def decode_payload(encrypted_value: str):
        """Decrypt first so a missing/wrong key aborts the atomic migration."""
        if not encrypted_value:
            return None
        try:
            plaintext = decrypt_value(encrypted_value)
        except UnicodeDecodeError:
            # The ciphertext decrypted, but its plaintext is not valid text.
            return None
        try:
            return json.loads(plaintext)
        except (json.JSONDecodeError, RecursionError):
            # A decrypted but malformed grant is unsafe and can be quarantined.
            return None

    def safe_payload(credential, server, endpoint: str, registration, payload):
        if (
            credential.oauth_status != "connected"
            or not credential.encrypted_value
            or credential.oauth_server_url != endpoint
            or not _resource_matches(endpoint, credential.oauth_resource)
            or not safe_registration(registration, endpoint, credential.oauth_resource)
        ):
            return None
        if not isinstance(payload, dict):
            return None
        if (
            not isinstance(payload.get("access_token"), str)
            or not payload["access_token"]
            or payload.get("server_id") != str(server.id)
            or payload.get("server_url") != endpoint
            or payload.get("resource") != credential.oauth_resource
            or payload.get("registration_id") != str(registration.id)
            or not isinstance(payload.get("identity", {}), dict)
        ):
            return None
        return payload

    # Quarantine a required requirement if it points at distinct endpoints.
    ambiguous_requirements = set()
    requirement_endpoints = {}
    for req in requirements:
        endpoints = {server.url for server in old_edges[req.id]["servers"]}
        requirement_endpoints[req.id] = endpoints
        if len(endpoints) > 1:
            ambiguous_requirements.add(req.id)

    requirement_targets = {}
    for service_id, service_reqs in requirements_by_service.items():
        service = services[service_id]
        endpoint_pairs = {}
        for req in service_reqs:
            if req.id in ambiguous_requirements:
                continue
            for server in old_edges[req.id]["servers"]:
                endpoint_pairs.setdefault(server.url, []).append((req, server))
        endpoint_targets = {}
        for index, endpoint in enumerate(sorted(endpoint_pairs)):
            if index == 0:
                target = service
            else:
                digest = hashlib.sha256(endpoint.encode()).hexdigest()[:12]
                suffix = f"-endpoint-{digest}"
                slug = f"{service.slug[: 255 - len(suffix)]}{suffix}"
                target_id = uuid.uuid5(_NAMESPACE, f"{service.id}:{endpoint}")
                target = Service.objects.filter(pk=target_id).first()
                if target is None:
                    if (
                        Service.objects.filter(
                            slug=slug, organization_id=service.organization_id
                        )
                        .exclude(pk=service.id)
                        .exists()
                    ):
                        suffix = f"-{target_id.hex[:24]}"
                        slug = f"{service.slug[: 255 - len(suffix)]}{suffix}"
                    target = Service.objects.create(
                        id=target_id,
                        organization_id=service.organization_id,
                        name=service.name,
                        slug=slug,
                        description=service.description,
                        credential_type="mcp_oauth",
                        env_var_name="",
                        target_path="",
                        label=service.label,
                        oauth_server_url=endpoint,
                    )
            target.oauth_server_url = endpoint
            target.save(update_fields=["oauth_server_url"])
            endpoint_targets[endpoint] = target.id
        for endpoint, pairs in endpoint_pairs.items():
            for req, _server in pairs:
                target_id = endpoint_targets[endpoint]
                Requirement.objects.filter(pk=req.id).update(
                    credential_service_id=target_id
                )
                requirement_targets[req.id] = target_id
        for req in service_reqs:
            if (
                req.id not in ambiguous_requirements
                and req.id not in requirement_targets
            ):
                urls = requirement_endpoints[req.id]
                if len(urls) == 1 and next(iter(urls)) in endpoint_targets:
                    target_id = endpoint_targets[next(iter(urls))]
                    Requirement.objects.filter(pk=req.id).update(
                        credential_service_id=target_id
                    )
                    requirement_targets[req.id] = target_id
            if req.id in ambiguous_requirements:
                digest = hashlib.sha256(
                    f"ambiguous:{service_id}:{req.id}".encode()
                ).hexdigest()[:16]
                suffix = f"-ambiguous-{digest}"
                slug = f"{service.slug[: 255 - len(suffix)]}{suffix}"
                target_id = uuid.uuid5(_NAMESPACE, f"ambiguous:{service_id}:{req.id}")
                target = Service.objects.filter(pk=target_id).first()
                if target is None:
                    if (
                        Service.objects.filter(
                            slug=slug, organization_id=service.organization_id
                        )
                        .exclude(pk=service.id)
                        .exists()
                    ):
                        suffix = f"-{target_id.hex[:24]}"
                        slug = f"{service.slug[: 255 - len(suffix)]}{suffix}"
                    target = Service.objects.create(
                        id=target_id,
                        organization_id=service.organization_id,
                        name=service.name,
                        slug=slug,
                        description=service.description,
                        credential_type="mcp_oauth",
                        env_var_name="",
                        target_path="",
                        label=service.label,
                        oauth_server_url="",
                    )
                Requirement.objects.filter(pk=req.id).update(
                    credential_service_id=target.id
                )
                requirement_targets[req.id] = target.id

    registrations = {row.id: row for row in Registration.objects.all()}
    credentials = (
        Credential.objects.filter(service__credential_type="mcp_oauth")
        .select_related("service", "oauth_registration")
        .order_by("id")
    )
    for credential in credentials:
        # Decryption failures (notably a missing or wrong encryption key) must
        # abort the atomic migration before any grant can be quarantined/cleared.
        decoded_payload = decode_payload(credential.encrypted_value)
        original_service = services.get(credential.service_id)
        server = servers.get(credential.oauth_server_id)
        registration = registrations.get(credential.oauth_registration_id)
        matching = []
        if original_service is not None and server is not None:
            for req in requirements_by_service.get(credential.service_id, []):
                edge = old_edges[req.id]
                if (
                    req.id not in ambiguous_requirements
                    and edge["required"]
                    and edge["service_id"] == credential.service_id
                    and edge["plugin_id"] == server.plugin_id
                    and edge["key"] == server.oauth_requirement_key
                    and any(old.id == server.id for old in edge["servers"])
                ):
                    matching.append(req)
        req = matching[0] if len(matching) == 1 else None
        plugin = plugins.get(server.plugin_id) if server else None
        endpoint = server.url if server else ""
        compatible = bool(
            original_service is not None
            and plugin is not None
            and (
                original_service.organization_id is None
                or original_service.organization_id == plugin.organization_id
            )
        )
        owner_safe = bool(
            original_service is not None
            and service_visible(original_service, credential)
            and plugin_visible(plugin, credential)
            and compatible
        )
        target_id = requirement_targets.get(req.id) if req else None
        payload = (
            safe_payload(
                credential, server, endpoint, registration, decoded_payload
            )
            if (req and target_id is not None and owner_safe)
            else None
        )
        if payload is not None:
            payload.pop("server_id", None)
            payload["service_id"] = str(target_id)
            credential.service_id = target_id
            credential.oauth_server_url = endpoint
            credential.encrypted_value = encrypt_value(json.dumps(payload))
            credential.save(
                update_fields=["service", "oauth_server_url", "encrypted_value"]
            )
        else:
            credential.oauth_status = "reconnect_required"
            credential.encrypted_value = ""
            if req and target_id is not None and owner_safe:
                credential.service_id = target_id
                credential.oauth_server_url = endpoint
                credential.save(
                    update_fields=[
                        "service",
                        "oauth_server_url",
                        "oauth_status",
                        "encrypted_value",
                    ]
                )
            else:
                credential.save(update_fields=["oauth_status", "encrypted_value"])

    for service in Service.objects.filter(credential_type="mcp_oauth"):
        organizations = (
            Organization.objects.filter(id=service.organization_id)
            if service.organization_id
            else Organization.objects.all()
        )
        Activation.objects.bulk_create(
            [
                Activation(organization_id=org.id, credential_service_id=service.id)
                for org in organizations
            ],
            ignore_conflicts=True,
        )
    notion = Service.objects.filter(
        slug="notion-notion_oauth-oauth",
        organization__isnull=True,
        credential_type="mcp_oauth",
    ).first()
    if (
        notion
        and not Service.objects.filter(slug="notion-oauth", organization__isnull=True)
        .exclude(id=notion.id)
        .exists()
    ):
        notion.slug = "notion-oauth"
        notion.save(update_fields=["slug"])
    State.objects.all().update(consumed_at=timezone.now(), expires_at=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0007_forward_repair_mcp_oauth_registration_auth_method"),
        ("plugins", "0007_repair_notion_mcp_oauth"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="credential", name="unique_personal_mcp_oauth_binding"
        ),
        migrations.RemoveConstraint(
            model_name="credential", name="unique_org_mcp_oauth_binding"
        ),
        migrations.AddField(
            model_name="credentialservice",
            name="oauth_server_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fixed HTTPS MCP resource endpoint for mcp_oauth services.",
                max_length=2048,
            ),
        ),
        migrations.AddField(
            model_name="mcpoauthauthorizationstate",
            name="credential",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oauth_authorization_states",
                to="credentials.credential",
            ),
        ),
        migrations.AddField(
            model_name="mcpoauthauthorizationstate",
            name="credential_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="mcpoauthauthorizationstate",
            name="credential_server_url_snapshot",
            field=models.CharField(blank=True, default="", max_length=2048),
        ),
        migrations.AddField(
            model_name="mcpoauthauthorizationstate",
            name="reconnect_existing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mcpoauthauthorizationstate",
            name="registration_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.RunPython(separate_legacy_oauth, migrations.RunPython.noop),
        migrations.RunPython(
            flush_deferred_constraints,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(model_name="credential", name="oauth_server_id"),
        migrations.RemoveField(
            model_name="credentialservice", name="oauth_plugin_slug"
        ),
        migrations.RemoveField(
            model_name="credentialservice", name="oauth_requirement_key"
        ),
        migrations.RemoveField(model_name="credentialservice", name="plugin_owned"),
        migrations.RemoveField(
            model_name="mcpoauthauthorizationstate", name="requirement_key"
        ),
        migrations.RemoveField(
            model_name="mcpoauthauthorizationstate", name="server_id"
        ),
    ]
