# Generated by Django 5.2.17 on 2026-10-01 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0008_plugin_credential_separation"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentialservice",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for global services; set for organization-owned services.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credential_services",
                to="organizations.organization",
            ),
        ),
    ]
