# Generated by Django 5.2.13 on 2026-10-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image_versions_to_keep',
            field=models.PositiveSmallIntegerField(db_default=2, default=2, help_text='Number of newest ready versions kept per image. Older versions are deleted automatically once no workspace is based on them.'),
        ),
    ]
