# Generated by Django 5.2.12 on 2026-04-01 17:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Short identifier (e.g. 'copilot'). Unique globally for standard definitions, unique per org for org-specific ones.", max_length=64)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of the agent.')),
                ('available_options', models.JSONField(blank=True, default=list, help_text='List of selectable options for this agent. Each entry is a dict with \'key\', \'label\', \'choices\' (list of strings), and \'default\' (string). Example: [{"key": "permission_mode", "label": "Permission Mode", "choices": ["default", "plan"], "default": "default"}]')),
                ('default_env', models.JSONField(blank=True, default=dict, help_text='Environment variables injected into every run command for this agent. Defined as a key/value dict. Example: {"ANTHROPIC_API_KEY": "sk-..."}. Per-command env vars in AgentCommand.env take precedence over these defaults.')),
                ('supports_multi_chat', models.BooleanField(default=False, help_text='Whether this agent supports multiple chat threads per workspace. When True, a {chat_id} placeholder in run command args is resolved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='The organization that owns this agent definition. Null means this is a standard/global definition.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_definitions', to='organizations.organization')),
                ('required_credential_services', models.ManyToManyField(blank=True, help_text='Credential services required to use this agent. Agents can only be selected for workspaces that already include all of these credential services.', related_name='agents', to='credentials.credentialservice')),
            ],
            options={
                'db_table': 'runners_agent_definition',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('configure', 'Configure'), ('run', 'Run'), ('run_first', 'Run (First Message)')], help_text="When this command is executed: 'configure' or 'run'.", max_length=20)),
                ('args', models.JSONField(help_text='Command arguments as a list of strings. May contain {prompt} and {workdir} placeholders.')),
                ('workdir', models.CharField(blank=True, help_text='Working directory. May contain {workdir} placeholder.', max_length=512, null=True)),
                ('env', models.JSONField(blank=True, default=dict, help_text='Extra environment variables for this command.')),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable description of what this command does.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Execution order within the same phase.')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='runners.agentdefinition')),
            ],
            options={
                'db_table': 'runners_agent_command',
                'ordering': ['agent', 'phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AgentDefinitionCredentialRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_env', models.JSONField(blank=True, default=dict, help_text="Environment variables to inject when this credential service is present. Applied before the AgentDefinition's own default_env.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_relations', to='runners.agentdefinition')),
                ('credential_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_relations', to='credentials.credentialservice')),
            ],
            options={
                'db_table': 'runners_agent_credential_relation',
                'ordering': ['agent_definition', 'credential_service'],
            },
        ),
        migrations.CreateModel(
            name='AgentCredentialRelationCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('configure', 'Configure'), ('run', 'Run'), ('run_first', 'Run (First Message)')], help_text="When this command is executed: 'configure' or 'run'.", max_length=20)),
                ('args', models.JSONField(help_text='Command arguments as a list of strings. May contain {prompt} and {workdir} placeholders.')),
                ('workdir', models.CharField(blank=True, help_text='Working directory. May contain {workdir} placeholder.', max_length=512, null=True)),
                ('env', models.JSONField(blank=True, default=dict, help_text='Extra environment variables for this command.')),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable description of what this command does.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Execution order within the same phase.')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='runners.agentdefinitioncredentialrelation')),
            ],
            options={
                'db_table': 'runners_agent_credential_relation_command',
                'ordering': ['relation', 'phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='Display name for the chat (auto-set from first prompt if empty).', max_length=255)),
                ('agent_type', models.CharField(blank=True, default='', help_text='Display snapshot of the selected agent name.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_definition', models.ForeignKey(blank=True, help_text='The selected agent definition for this chat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='runners.agentdefinition')),
            ],
            options={
                'db_table': 'runners_chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('runtime_type', models.CharField(choices=[('docker', 'Docker'), ('qemu', 'QEMU/KVM')], default='docker', max_length=20)),
                ('base_distro', models.CharField(default='ubuntu:22.04', max_length=255)),
                ('packages', models.JSONField(blank=True, default=list)),
                ('env_vars', models.JSONField(blank=True, default=dict)),
                ('custom_dockerfile', models.TextField(blank=True, default='')),
                ('custom_init_script', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_image_definitions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='The organization that owns this image definition. Null means this is a standard/global definition.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_definitions', to='organizations.organization')),
            ],
            options={
                'db_table': 'runners_image_definition',
                'ordering': ['name', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgAgentDefinitionActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_activations', to='runners.agentdefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_activations', to='organizations.organization')),
            ],
            options={
                'db_table': 'runners_org_agent_activation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('api_token_hash', models.CharField(help_text="SHA-256 hash of the runner's API token.", max_length=64, unique=True)),
                ('available_runtimes', models.JSONField(blank=True, default=list, help_text="List of runtime types this runner supports (e.g. ['docker', 'qemu']).")),
                ('qemu_min_vcpus', models.PositiveSmallIntegerField(default=1)),
                ('qemu_max_vcpus', models.PositiveSmallIntegerField(default=8)),
                ('qemu_default_vcpus', models.PositiveSmallIntegerField(default=2)),
                ('qemu_min_memory_mb', models.PositiveIntegerField(default=1024)),
                ('qemu_max_memory_mb', models.PositiveIntegerField(default=16384)),
                ('qemu_default_memory_mb', models.PositiveIntegerField(default=4096)),
                ('qemu_min_disk_size_gb', models.PositiveIntegerField(default=20)),
                ('qemu_max_disk_size_gb', models.PositiveIntegerField(default=200)),
                ('qemu_default_disk_size_gb', models.PositiveIntegerField(default=50)),
                ('qemu_max_active_vcpus', models.PositiveIntegerField(blank=True, help_text='Optional cap for total vCPUs across active (running) QEMU workspaces.', null=True)),
                ('qemu_max_active_memory_mb', models.PositiveIntegerField(blank=True, help_text='Optional cap for total RAM (MiB) across active QEMU workspaces.', null=True)),
                ('qemu_max_active_disk_size_gb', models.PositiveIntegerField(blank=True, help_text='Optional cap for total disk size (GiB) across active QEMU workspaces.', null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('sid', models.CharField(blank=True, default='', help_text='Socket.IO session ID for sending targeted messages.', max_length=255)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='Timestamp of the last heartbeat received from this runner.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='organizations.organization')),
            ],
            options={
                'db_table': 'runners_runner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunnerSystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='UTC timestamp when these metrics were recorded.')),
                ('cpu_usage_percent', models.FloatField(help_text='Mean CPU utilisation across all cores (0–100).')),
                ('ram_used_bytes', models.BigIntegerField(help_text='RAM currently in use (bytes).')),
                ('ram_total_bytes', models.BigIntegerField(help_text='Total installed RAM (bytes).')),
                ('disk_used_bytes', models.BigIntegerField(help_text='Disk space used on the root filesystem (bytes).')),
                ('disk_total_bytes', models.BigIntegerField(help_text='Total disk capacity of the root filesystem (bytes).')),
                ('vm_metrics', models.JSONField(blank=True, help_text='Per-VM usage metrics keyed by workspace ID.', null=True)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_metrics', to='runners.runner')),
            ],
            options={
                'db_table': 'runners_system_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('agent_model', models.CharField(blank=True, default='', max_length=128)),
                ('agent_options', models.JSONField(blank=True, default=dict, help_text='Selected agent options for this session as a key/value dict. Example: {"model": "claude-opus-4.6", "permission_mode": "plan"}')),
                ('output', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the user opened this completed/failed session.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='runners.chat')),
            ],
            options={
                'db_table': 'runners_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('create_workspace', 'Create Workspace'), ('update_workspace', 'Update Workspace'), ('run_prompt', 'Run Prompt'), ('cancel_session', 'Cancel Session'), ('stop_workspace', 'Stop Workspace'), ('resume_workspace', 'Resume Workspace'), ('remove_workspace', 'Remove Workspace'), ('start_terminal', 'Start Terminal'), ('create_image_artifact', 'Create Image Artifact'), ('create_workspace_from_image_artifact', 'Create Workspace From Image Artifact'), ('build_image', 'Build Image')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='runners.runner')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='runners.session')),
            ],
            options={
                'db_table': 'runners_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunnerImageBuild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('active', 'Active'), ('failed', 'Failed'), ('deactivated', 'Deactivated')], default='pending', max_length=20)),
                ('image_tag', models.CharField(blank=True, default='', max_length=255)),
                ('image_path', models.CharField(blank=True, default='', max_length=512)),
                ('build_log', models.TextField(blank=True, default='')),
                ('built_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_builds', to='runners.imagedefinition')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_builds', to='runners.runner')),
                ('build_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_image_builds', to='runners.task')),
            ],
            options={
                'db_table': 'runners_runner_image_build',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runtime_type', models.CharField(choices=[('docker', 'Docker'), ('qemu', 'QEMU/KVM')], default='docker', help_text="Virtualisation backend: 'docker' or 'qemu'.", max_length=20)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('removed', 'Removed')], default='creating', max_length=20)),
                ('active_operation', models.CharField(blank=True, choices=[('creating', 'Creating'), ('starting', 'Starting'), ('stopping', 'Stopping'), ('restarting', 'Restarting'), ('removing', 'Removing'), ('capturing_image', 'Capturing Image')], max_length=32, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('qemu_vcpus', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('qemu_memory_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('qemu_disk_size_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the most recent user- or session-driven activity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
                ('credentials', models.ManyToManyField(blank=True, help_text='Credentials currently attached to this workspace. These are used when checking agent availability and when injecting env vars or SSH keys into the workspace runtime.', related_name='workspaces', to='credentials.credential')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='runners.runner')),
            ],
            options={
                'db_table': 'runners_workspace',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='runners.workspace'),
        ),
        migrations.CreateModel(
            name='ImageArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_kind', models.CharField(choices=[('captured', 'Captured'), ('built', 'Built')], default='captured', max_length=20)),
                ('runner_artifact_id', models.CharField(blank=True, default='', help_text='Artifact identifier on the runner. Empty while creating.', max_length=255)),
                ('name', models.CharField(help_text='Human-readable artifact name.', max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0, help_text='Artifact size in bytes.')),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', help_text='Artifact status: creating (in progress), ready (available), failed.', max_length=20)),
                ('creating_task_id', models.CharField(blank=True, db_index=True, help_text='Task ID of the creation task, used to link runner events back to this record.', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this artifact.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_artifacts', to=settings.AUTH_USER_MODEL)),
                ('credentials', models.ManyToManyField(blank=True, help_text='Credentials attached when the artifact was created. Used to automatically restore credentials when creating a workspace from this artifact.', related_name='image_artifacts', to='credentials.credential')),
                ('runner_image_build', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact', to='runners.runnerimagebuild')),
                ('source_workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_artifacts', to='runners.workspace')),
            ],
            options={
                'db_table': 'runners_image_artifact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='runners.workspace'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('name',), name='unique_standard_agent_name'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('name', 'organization'), name='unique_org_agent_name'),
        ),
        migrations.AddConstraint(
            model_name='agentcommand',
            constraint=models.UniqueConstraint(condition=models.Q(('phase', 'run')), fields=('agent', 'phase'), name='unique_run_command_per_agent'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinitioncredentialrelation',
            constraint=models.UniqueConstraint(fields=('agent_definition', 'credential_service'), name='unique_agent_credential_relation'),
        ),
        migrations.AddConstraint(
            model_name='imagedefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('name',), name='unique_standard_image_definition_name'),
        ),
        migrations.AddConstraint(
            model_name='imagedefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('name', 'organization'), name='unique_org_image_definition_name'),
        ),
        migrations.AddConstraint(
            model_name='orgagentdefinitionactivation',
            constraint=models.UniqueConstraint(fields=('organization', 'agent_definition'), name='unique_org_agent_activation'),
        ),
        migrations.AddIndex(
            model_name='runnersystemmetrics',
            index=models.Index(fields=['runner', '-timestamp'], name='runner_metrics_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='runnerimagebuild',
            constraint=models.UniqueConstraint(fields=('image_definition', 'runner'), name='uniq_runner_image_build_definition_runner'),
        ),
    ]
