# Generated by Django 5.2.12 on 2026-04-02

import uuid

from django.db import migrations


AGENT_SEEDS = [
    {
        "id": "3c1a9bae-cd1c-4fdb-988e-2a6bb667038b",
        "name": "Claude Code",
        "description": "",
        "available_options": [
            {
                "key": "model",
                "label": "Model",
                "choices": [
                    "claude-opus-4-5",
                    "claude-sonnet-4-5",
                    "claude-haiku-4-5",
                    "claude-opus-4-6",
                    "claude-sonnet-4-6",
                ],
                "default": "claude-sonnet-4-6",
            },
            {
                "key": "permission_mode",
                "label": "Permission Mode",
                "choices": [
                    "default",
                    "acceptEdits",
                    "bypassPermissions",
                    "dontAsk",
                    "plan",
                ],
                "default": "bypassPermissions",
            },
        ],
        "default_env": {"IS_SANDBOX": 1},
        "supports_multi_chat": True,
        "required_credential_service_slugs": ["claude-oauth-token"],
        "credential_relations": [
            {
                "id": "2283efd9-ab8f-45a1-af7a-7e164babae5a",
                "credential_service_slug": "claude-oauth-token",
                "default_env": {},
            }
        ],
        "commands": [
            {
                "id": "01a21387-40e2-4a9d-b3bb-7044133efbc1",
                "phase": "configure",
                "args": ["curl", "-fsSL", "https://claude.ai/install.sh", "|", "bash"],
                "workdir": "/workspace",
                "env": {},
                "description": "Install Claude Code",
                "order": 0,
            },
            {
                "id": "45d1c831-f3ee-44e4-94fd-c974f9e468e7",
                "phase": "run",
                "args": [
                    "/root/.local/bin/claude",
                    "--resume",
                    "0af7372f-cb60-4e27-ae07-52937443aeb3",
                    "--model",
                    "gpt-5.3-codex",
                    "--permission-mode",
                    "{permission_mode}",
                    "--print",
                    "{prompt}",
                ],
                "workdir": "/workspace",
                "env": {},
                "description": "Run prompt with Claude Code",
                "order": 1,
            },
            {
                "id": "85e77764-a1c5-4dc0-a71c-0a8139e42841",
                "phase": "run_first",
                "args": [
                    "/root/.local/bin/claude",
                    "--session-id",
                    "0af7372f-cb60-4e27-ae07-52937443aeb3",
                    "--model",
                    "gpt-5.3-codex",
                    "--permission-mode",
                    "{permission_mode}",
                    "--print",
                    "{prompt}",
                ],
                "workdir": "/workspace",
                "env": {},
                "description": "Run first prompt with Claude Code (initialises session)",
                "order": 2,
            },
        ],
    },
    {
        "id": "f8168b23-f56a-42dd-bef2-15301148b382",
        "name": "Codex CLI",
        "description": "",
        "available_options": [
            {
                "key": "model",
                "label": "Model",
                "choices": [
                    "gpt-5.4",
                    "gpt-5.3-codex",
                    "gpt-5.2-codex",
                    "gpt-5.1-codex",
                    "gpt-5.1-codex-mini",
                    "gpt-5-codex-mini",
                    "gpt-5.3-codex-spark",
                    "o3",
                    "o3-mini",
                    "o4-mini",
                    "gpt-4.1",
                    "gpt-4.1-mini",
                    "gpt-4o",
                    "gpt-4o-mini",
                ],
                "default": "gpt-5.4",
            }
        ],
        "default_env": {},
        "supports_multi_chat": False,
        "required_credential_service_slugs": [],
        "credential_relations": [],
        "commands": [
            {
                "id": "366dcba8-77dd-472c-96e3-791ff82865c9",
                "phase": "configure",
                "args": ["npm", "i", "-g", "@openai/codex"],
                "workdir": "/workspace",
                "env": {},
                "description": "Install Codex",
                "order": 0,
            },
            {
                "id": "2c5572e9-b314-4bd4-80e1-a123082ac96a",
                "phase": "run",
                "args": [
                    "codex",
                    "exec",
                    "resume",
                    "--last",
                    "--model",
                    "gpt-5.3-codex",
                    "--dangerously-bypass-approvals-and-sandbox",
                    "{prompt}",
                    "2>/dev/null",
                ],
                "workdir": "/workspace",
                "env": {},
                "description": "Run prompt",
                "order": 1,
            },
            {
                "id": "a3816c9a-fbb2-4a98-bc1a-e166461764ce",
                "phase": "run_first",
                "args": [
                    "codex",
                    "exec",
                    "--model",
                    "gpt-5.3-codex",
                    "--dangerously-bypass-approvals-and-sandbox",
                    "{prompt}",
                    "2>/dev/null",
                ],
                "workdir": "/workspace",
                "env": {},
                "description": "Run first prompt",
                "order": 2,
            },
        ],
    },
    {
        "id": "c139900b-8840-4666-812d-cd3a9ed71844",
        "name": "GitHub Copilot",
        "description": "",
        "available_options": [
            {
                "key": "model",
                "label": "Model",
                "choices": [
                    "claude-sonnet-4.6",
                    "claude-sonnet-4.5",
                    "claude-haiku-4.5",
                    "claude-opus-4.6",
                    "claude-opus-4.6-fast",
                    "claude-opus-4.5",
                    "claude-sonnet-4",
                    "gemini-3-pro-preview",
                    "gemini-3.1-pro-preview",
                    "gpt-5.3-codex",
                    "gpt-5.2-codex",
                    "gpt-5.2",
                    "gpt-5.1-codex-max",
                    "gpt-5.1-codex",
                    "gpt-5.1",
                    "gpt-5",
                    "gpt-5.1-codex-mini",
                    "gpt-5-mini",
                    "gpt-4.1",
                ],
                "default": "claude-sonnet-4.6",
            }
        ],
        "default_env": {},
        "supports_multi_chat": True,
        "required_credential_service_slugs": ["github"],
        "credential_relations": [
            {
                "id": "29e2123a-ebc0-41cb-9a9e-5ac1652beb48",
                "credential_service_slug": "github",
                "default_env": {},
            }
        ],
        "commands": [
            {
                "id": "32dd0d52-efda-4d2a-84b5-b67479402bbb",
                "phase": "configure",
                "args": ["npm", "install", "-g", "@github/copilot"],
                "workdir": "/workspace",
                "env": {},
                "description": "Install GitHub Copilot CLI",
                "order": 0,
            },
            {
                "id": "6d445511-f21e-403c-962a-d5f197e843c9",
                "phase": "run",
                "args": [
                    "copilot",
                    "--resume",
                    "0af7372f-cb60-4e27-ae07-52937443aeb3",
                    "--model",
                    "gpt-5.3-codex",
                    "--stream",
                    "on",
                    "-p",
                    "{prompt}",
                    "--allow-all-tools",
                    "--silent",
                ],
                "workdir": "/workspace",
                "env": {},
                "description": "Run prompt with Copilot CLI",
                "order": 1,
            },
        ],
    },
    {
        "id": "b478907f-c6b3-41af-9fd4-90ac90becad7",
        "name": "GitHub Copilot Student",
        "description": "",
        "available_options": [
            {
                "key": "model",
                "label": "Model",
                "choices": [
                    "claude-haiku-4.5",
                    "gemini-3.1-pro-preview",
                    "gpt-5.3-codex",
                    "gpt-5.2-codex",
                    "gpt-5.2",
                    "gpt-5.1-codex-max",
                    "gpt-5.1-codex",
                    "gpt-5.1",
                    "gpt-5",
                    "gpt-5.1-codex-mini",
                    "gpt-5-mini",
                    "gpt-4.1",
                ],
                "default": "gpt-5.3-codex",
            }
        ],
        "default_env": {},
        "supports_multi_chat": True,
        "required_credential_service_slugs": ["github"],
        "credential_relations": [
            {
                "id": "ed9065af-c9bf-456c-8066-50c156d6c1cb",
                "credential_service_slug": "github",
                "default_env": {},
            }
        ],
        "commands": [
            {
                "id": "28eaa455-4909-4a1b-99c3-0e35f007d47a",
                "phase": "configure",
                "args": ["npm", "install", "-g", "@github/copilot"],
                "workdir": "/workspace",
                "env": {},
                "description": "Install GitHub Copilot CLI",
                "order": 0,
            },
            {
                "id": "b7e80660-e534-4c2f-bc15-eac411203b8d",
                "phase": "run",
                "args": [
                    "copilot",
                    "--resume",
                    "0af7372f-cb60-4e27-ae07-52937443aeb3",
                    "--model",
                    "gpt-5.3-codex",
                    "--stream",
                    "on",
                    "-p",
                    "{prompt}",
                    "--allow-all-tools",
                    "--silent",
                ],
                "workdir": "/workspace",
                "env": {},
                "description": "Run prompt with Copilot CLI",
                "order": 1,
            },
        ],
    },
]


IMAGE_SEEDS = [
    {
        "id": "3ecafbe4-d2e5-4d3e-84df-6c5b8741a24d",
        "name": "Ubuntu 24.04 Docker",
        "description": "",
        "runtime_type": "docker",
        "base_distro": "ubuntu:24.04",
        "packages": ["python3", "git"],
        "env_vars": {},
        "custom_dockerfile": "RUN apt-get update && apt-get install -y curl ca-certificates gnupg ",
        "custom_init_script": "",
        "is_active": True,
    },
    {
        "id": "2025335b-0e41-4baf-89b9-a7281a4fd62f",
        "name": "Ubuntu 24.04",
        "description": "",
        "runtime_type": "qemu",
        "base_distro": "ubuntu:24.04",
        "packages": ["python3", "git"],
        "env_vars": {},
        "custom_dockerfile": "",
        "custom_init_script": "#!/bin/bash\n\necho \"=== Installing Node.js 22.x ===\"\ncurl -fsSL https://deb.nodesource.com/setup_22.x | bash -\napt-get install -y nodejs\nnpm install -g npm@latest",
        "is_active": True,
    },
]


def _upsert_agent(agent_model, seed):
    agent = (
        agent_model.objects.filter(id=seed["id"]).first()
        or agent_model.objects.filter(name=seed["name"], organization__isnull=True).first()
    )

    if agent is None:
        return agent_model.objects.create(
            id=uuid.UUID(seed["id"]),
            organization=None,
            name=seed["name"],
            description=seed["description"],
            available_options=seed["available_options"],
            default_env=seed["default_env"],
            supports_multi_chat=seed["supports_multi_chat"],
        )

    agent.organization = None
    agent.name = seed["name"]
    agent.description = seed["description"]
    agent.available_options = seed["available_options"]
    agent.default_env = seed["default_env"]
    agent.supports_multi_chat = seed["supports_multi_chat"]
    agent.save()
    return agent


def _upsert_agent_command(agent_command_model, agent, command_seed):
    command = (
        agent_command_model.objects.filter(id=command_seed["id"]).first()
        or agent_command_model.objects.filter(
            agent=agent,
            phase=command_seed["phase"],
            order=command_seed["order"],
        ).first()
    )

    if command is None:
        agent_command_model.objects.create(
            id=uuid.UUID(command_seed["id"]),
            agent=agent,
            phase=command_seed["phase"],
            args=command_seed["args"],
            workdir=command_seed["workdir"],
            env=command_seed["env"],
            description=command_seed["description"],
            order=command_seed["order"],
        )
        return

    command.agent = agent
    command.phase = command_seed["phase"]
    command.args = command_seed["args"]
    command.workdir = command_seed["workdir"]
    command.env = command_seed["env"]
    command.description = command_seed["description"]
    command.order = command_seed["order"]
    command.save()


def _upsert_image_definition(image_definition_model, seed):
    image = (
        image_definition_model.objects.filter(id=seed["id"]).first()
        or image_definition_model.objects.filter(
            name=seed["name"], organization__isnull=True
        ).first()
    )

    if image is None:
        return image_definition_model.objects.create(
            id=uuid.UUID(seed["id"]),
            organization=None,
            created_by=None,
            name=seed["name"],
            description=seed["description"],
            runtime_type=seed["runtime_type"],
            base_distro=seed["base_distro"],
            packages=seed["packages"],
            env_vars=seed["env_vars"],
            custom_dockerfile=seed["custom_dockerfile"],
            custom_init_script=seed["custom_init_script"],
            is_active=seed["is_active"],
        )

    image.organization = None
    image.created_by = None
    image.name = seed["name"]
    image.description = seed["description"]
    image.runtime_type = seed["runtime_type"]
    image.base_distro = seed["base_distro"]
    image.packages = seed["packages"]
    image.env_vars = seed["env_vars"]
    image.custom_dockerfile = seed["custom_dockerfile"]
    image.custom_init_script = seed["custom_init_script"]
    image.is_active = seed["is_active"]
    image.save()
    return image


def seed_global_agent_and_image_definitions(apps, schema_editor):
    agent_model = apps.get_model("runners", "AgentDefinition")
    agent_command_model = apps.get_model("runners", "AgentCommand")
    relation_model = apps.get_model("runners", "AgentDefinitionCredentialRelation")
    image_definition_model = apps.get_model("runners", "ImageDefinition")
    organization_model = apps.get_model("organizations", "Organization")
    agent_activation_model = apps.get_model("runners", "OrgAgentDefinitionActivation")
    credential_service_model = apps.get_model("credentials", "CredentialService")
    seeded_agents = []

    for agent_seed in AGENT_SEEDS:
        agent = _upsert_agent(agent_model, agent_seed)
        seeded_agents.append(agent)

        required_services = list(
            credential_service_model.objects.filter(
                slug__in=agent_seed["required_credential_service_slugs"]
            )
        )
        agent.required_credential_services.set(required_services)

        for relation_seed in agent_seed["credential_relations"]:
            credential_service = credential_service_model.objects.filter(
                slug=relation_seed["credential_service_slug"]
            ).first()
            if credential_service is None:
                continue

            relation = (
                relation_model.objects.filter(id=relation_seed["id"]).first()
                or relation_model.objects.filter(
                    agent_definition=agent,
                    credential_service=credential_service,
                ).first()
            )
            if relation is None:
                relation_model.objects.create(
                    id=uuid.UUID(relation_seed["id"]),
                    agent_definition=agent,
                    credential_service=credential_service,
                    default_env=relation_seed["default_env"],
                )
            else:
                relation.agent_definition = agent
                relation.credential_service = credential_service
                relation.default_env = relation_seed["default_env"]
                relation.save()

        for command_seed in agent_seed["commands"]:
            _upsert_agent_command(agent_command_model, agent, command_seed)

    for image_seed in IMAGE_SEEDS:
        _upsert_image_definition(image_definition_model, image_seed)

    organizations = list(organization_model.objects.all())
    agent_activation_model.objects.bulk_create(
        [
            agent_activation_model(organization=org, agent_definition=agent)
            for org in organizations
            for agent in seeded_agents
        ],
        ignore_conflicts=True,
    )


def unseed_global_agent_and_image_definitions(apps, schema_editor):
    agent_model = apps.get_model("runners", "AgentDefinition")
    image_definition_model = apps.get_model("runners", "ImageDefinition")

    agent_model.objects.filter(id__in=[uuid.UUID(seed["id"]) for seed in AGENT_SEEDS]).delete()
    image_definition_model.objects.filter(
        id__in=[uuid.UUID(seed["id"]) for seed in IMAGE_SEEDS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0002_seed_global_credential_services"),
        ("runners", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            seed_global_agent_and_image_definitions,
            unseed_global_agent_and_image_definitions,
        ),
    ]
