# Generated by Django 5.2.13 on 2026-04-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0003_fix_standard_qemu_image_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('create_workspace', 'Create Workspace'), ('update_workspace', 'Update Workspace'), ('run_prompt', 'Run Prompt'), ('cancel_session', 'Cancel Session'), ('stop_workspace', 'Stop Workspace'), ('resume_workspace', 'Resume Workspace'), ('remove_workspace', 'Remove Workspace'), ('start_terminal', 'Start Terminal'), ('start_desktop', 'Start Desktop'), ('stop_desktop', 'Stop Desktop'), ('create_image_artifact', 'Create Image Artifact'), ('create_workspace_from_image_artifact', 'Create Workspace From Image Artifact'), ('build_image', 'Build Image')], max_length=40),
        ),
    ]
