# Generated by Django 5.2.13 on 2026-04-10 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _table_exists(schema_editor, table_name):
    return table_name in schema_editor.connection.introspection.table_names()


def _ensure_table(schema_editor, model):
    if not _table_exists(schema_editor, model._meta.db_table):
        schema_editor.create_model(model)


def _copy_image_artifacts_forward(apps, schema_editor):
    ImageArtifact = apps.get_model("runners", "ImageArtifact")
    ImageDefinition = apps.get_model("runners", "ImageDefinition")
    ImageInstance = apps.get_model("runners", "ImageInstance")
    RunnerImageBuild = apps.get_model("runners", "RunnerImageBuild")
    Workspace = apps.get_model("runners", "Workspace")

    old_m2m = ImageArtifact.credentials.through
    new_m2m = ImageInstance.credentials.through

    _ensure_table(schema_editor, old_m2m)

    status_map = {
        "creating": "capturing",
        "ready": "ready",
        "failed": "failed",
    }

    for artifact in ImageArtifact.objects.select_related(
        "source_workspace__runner",
        "runner_image_build__runner",
        "runner_image_build__image_definition",
    ):
        build = artifact.runner_image_build
        workspace = artifact.source_workspace
        if build is not None:
            runner = build.runner
            runtime_type = build.image_definition.runtime_type
            origin_type = "definition_build"
            origin_definition = build.image_definition
            origin_workspace = None
            status = {
                "creating": "building",
                "ready": "ready",
                "failed": "failed",
            }[artifact.status]
            runner_ref = artifact.runner_artifact_id or build.image_tag or build.image_path
        elif workspace is not None:
            runner = workspace.runner
            runtime_type = workspace.runtime_type
            origin_type = "workspace_capture"
            origin_definition = None
            origin_workspace = workspace
            status = status_map[artifact.status]
            runner_ref = artifact.runner_artifact_id
        else:
            continue

        ImageInstance.objects.create(
            id=artifact.id,
            runner=runner,
            runtime_type=runtime_type,
            origin_type=origin_type,
            origin_definition=origin_definition,
            origin_workspace=origin_workspace,
            build_job=build,
            created_by=artifact.created_by,
            runner_ref=runner_ref,
            name=artifact.name,
            size_bytes=artifact.size_bytes,
            status=status,
            creating_task_id=artifact.creating_task_id,
            created_at=artifact.created_at,
            updated_at=artifact.created_at,
        )

    for rel in old_m2m.objects.all():
        new_m2m.objects.get_or_create(
            imageinstance_id=rel.imageartifact_id,
            credential_id=rel.credential_id,
        )

    existing_build_ids = set(
        ImageInstance.objects.exclude(build_job_id__isnull=True).values_list(
            "build_job_id",
            flat=True,
        )
    )
    for build in RunnerImageBuild.objects.select_related(
        "runner",
        "image_definition",
    ):
        if build.id in existing_build_ids:
            continue
        runner_ref = build.image_tag or build.image_path
        if not runner_ref:
            continue
        status = {
            "pending": "building",
            "building": "building",
            "active": "ready",
            "failed": "failed",
            "deactivated": "retired",
        }[build.status]
        ImageInstance.objects.create(
            runner=build.runner,
            runtime_type=build.image_definition.runtime_type,
            origin_type="definition_build",
            origin_definition=build.image_definition,
            origin_workspace=None,
            build_job=build,
            created_by=build.image_definition.created_by,
            runner_ref=runner_ref,
            name=f"{build.image_definition.name} ({build.runner.name})",
            size_bytes=0,
            status=status,
            creating_task_id=str(build.build_task_id) if build.build_task_id else None,
            created_at=build.created_at,
            updated_at=build.updated_at,
        )

    # Existing workspaces cannot be reconstructed reliably; keep them null.
    Workspace.objects.filter(base_image_instance_id__isnull=False).update(
        base_image_instance_id=None
    )


def _copy_image_artifacts_backward(apps, schema_editor):
    ImageArtifact = apps.get_model("runners", "ImageArtifact")
    ImageInstance = apps.get_model("runners", "ImageInstance")

    old_m2m = ImageArtifact.credentials.through
    new_m2m = ImageInstance.credentials.through

    for image in ImageInstance.objects.select_related(
        "origin_workspace",
        "build_job",
    ):
        if image.origin_type == "definition_build":
            artifact_kind = "built"
            source_workspace = None
            runner_image_build = image.build_job
            status = {
                "building": "creating",
                "ready": "ready",
                "retired": "ready",
                "deleting": "ready",
                "deleted": "failed",
                "failed": "failed",
                "capturing": "creating",
            }[image.status]
        else:
            artifact_kind = "captured"
            source_workspace = image.origin_workspace
            runner_image_build = None
            status = {
                "capturing": "creating",
                "ready": "ready",
                "retired": "ready",
                "deleting": "ready",
                "deleted": "failed",
                "failed": "failed",
                "building": "creating",
            }[image.status]

        ImageArtifact.objects.create(
            id=image.id,
            source_workspace=source_workspace,
            created_by=image.created_by,
            artifact_kind=artifact_kind,
            runner_image_build=runner_image_build,
            runner_artifact_id=image.runner_ref,
            name=image.name,
            size_bytes=image.size_bytes,
            status=status,
            creating_task_id=image.creating_task_id,
            created_at=image.created_at,
        )

    for rel in new_m2m.objects.all():
        old_m2m.objects.get_or_create(
            imageartifact_id=rel.imageinstance_id,
            credential_id=rel.credential_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_seed_global_credential_services'),
        ('runners', '0003_fix_standard_qemu_image_definition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('create_workspace', 'Create Workspace'), ('update_workspace', 'Update Workspace'), ('run_prompt', 'Run Prompt'), ('cancel_session', 'Cancel Session'), ('stop_workspace', 'Stop Workspace'), ('resume_workspace', 'Resume Workspace'), ('remove_workspace', 'Remove Workspace'), ('start_terminal', 'Start Terminal'), ('create_image_artifact', 'Create Image Artifact'), ('delete_image', 'Delete Image'), ('create_workspace_from_image_artifact', 'Create Workspace From Image Artifact'), ('build_image', 'Build Image')], max_length=40),
        ),
        migrations.CreateModel(
            name='ImageInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runtime_type', models.CharField(choices=[('docker', 'Docker'), ('qemu', 'QEMU/KVM')], default='docker', max_length=20)),
                ('origin_type', models.CharField(choices=[('definition_build', 'Definition Build'), ('workspace_capture', 'Workspace Capture')], default='workspace_capture', max_length=32)),
                ('runner_ref', models.CharField(blank=True, default='', help_text='Concrete runtime reference on the runner, e.g. a Docker image tag or QCOW2 path.', max_length=512)),
                ('name', models.CharField(help_text='Human-readable image instance name.', max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0, help_text='Image instance size in bytes.')),
                ('status', models.CharField(choices=[('building', 'Building'), ('capturing', 'Capturing'), ('ready', 'Ready'), ('retired', 'Retired'), ('deleting', 'Deleting'), ('deleted', 'Deleted'), ('failed', 'Failed')], default='ready', help_text='Lifecycle status of the image instance.', max_length=20)),
                ('creating_task_id', models.CharField(blank=True, db_index=True, help_text='Task ID of the creation/build task.', max_length=64, null=True)),
                ('deleting_task_id', models.CharField(blank=True, db_index=True, help_text='Task ID of the delete task while cleanup is pending.', max_length=64, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this image instance.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_instances', to=settings.AUTH_USER_MODEL)),
                ('credentials', models.ManyToManyField(blank=True, help_text='Credentials attached when the image instance was created. Used to automatically restore credentials when cloning from it.', related_name='image_instances', to='credentials.credential')),
                ('origin_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_instances', to='runners.imagedefinition')),
                ('origin_workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_image_instances', to='runners.workspace')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_instances', to='runners.runner')),
                ('build_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_instance', to='runners.runnerimagebuild')),
            ],
            options={
                'db_table': 'runners_image_instance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='base_image_instance',
            field=models.ForeignKey(blank=True, help_text='The concrete runtime image this workspace was created from. Legacy workspaces created before image-instance tracking may be null.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_workspaces', to='runners.imageinstance'),
        ),
        migrations.RunPython(
            _copy_image_artifacts_forward,
            _copy_image_artifacts_backward,
        ),
        migrations.DeleteModel(
            name='ImageArtifact',
        ),
    ]
