# Generated by Django 5.2.13 on 2026-04-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0003_fix_standard_qemu_image_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageartifact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the artifact was marked as deleted.', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='base_image_artifact',
            field=models.ForeignKey(blank=True, help_text='The image artifact this workspace was created from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_workspaces', to='runners.imageartifact'),
        ),
        migrations.AlterField(
            model_name='imageartifact',
            name='status',
            field=models.CharField(choices=[('creating', 'Creating'), ('ready', 'Ready'), ('failed', 'Failed'), ('retired', 'Retired'), ('pending_delete', 'Pending Delete'), ('deleted', 'Deleted')], default='ready', help_text='Artifact status: creating (in progress), ready (available), failed.', max_length=20),
        ),
    ]
