# Generated by Django 5.2.13 on 2026-04-11 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runners", "0004_alter_task_type_imageinstance_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="runnerimagebuild",
            name="uniq_runner_image_build_definition_runner",
        ),
        migrations.RenameModel(
            old_name="RunnerImageBuild",
            new_name="ImageBuildJob",
        ),
        migrations.AlterModelTable(
            name="imagebuildjob",
            table="runners_build_job",
        ),
        migrations.AlterField(
            model_name="imageinstance",
            name="build_job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="image_instance",
                to="runners.imagebuildjob",
            ),
        ),
        migrations.AlterField(
            model_name="imagebuildjob",
            name="build_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="build_jobs",
                to="runners.task",
            ),
        ),
        migrations.RemoveField(
            model_name="imagebuildjob",
            name="image_path",
        ),
        migrations.RemoveField(
            model_name="imagebuildjob",
            name="image_tag",
        ),
        migrations.AddConstraint(
            model_name="imagebuildjob",
            constraint=models.UniqueConstraint(
                fields=("image_definition", "runner"),
                name="uniq_build_job_definition_runner",
            ),
        ),
    ]
