# Generated by Django 5.2.13 on 2026-04-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0005_rename_runnerimagebuild_to_imagebuildjob'),
        ('runners', '0006_require_codex_auth_for_codex_cli'),
    ]

    operations = [
    ]
