# Generated by Django 5.2.13 on 2026-04-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0005_rename_runnerimagebuild_to_imagebuildjob'),
        ('runners', '0007_merge_0006_imageartifact_and_codex_auth'),
    ]

    operations = [
    ]
