# Generated by Django 5.2.13 on 2026-04-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0007_merge_20260418_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebuildjob',
            name='delete_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagebuildjob',
            name='delete_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagebuildjob',
            name='delete_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='imagebuildjob',
            name='delete_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagebuildjob',
            name='delete_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagebuildjob',
            name='deleting_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Task ID of the delete task while cleanup is pending.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='imagedefinition',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagedefinition',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagedefinition',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('pending_deletion', 'Pending Deletion'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='active', help_text='Lifecycle status of the image definition.', max_length=20),
        ),
        migrations.AddField(
            model_name='imageinstance',
            name='delete_attempt_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of deletion attempts.'),
        ),
        migrations.AddField(
            model_name='imageinstance',
            name='delete_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the runner confirmed deletion.', null=True),
        ),
        migrations.AddField(
            model_name='imageinstance',
            name='delete_last_error',
            field=models.TextField(blank=True, default='', help_text='Last error message from a deletion attempt.'),
        ),
        migrations.AddField(
            model_name='imageinstance',
            name='delete_requested_at',
            field=models.DateTimeField(blank=True, help_text='When deletion was first requested.', null=True),
        ),
        migrations.AddField(
            model_name='imageinstance',
            name='delete_started_at',
            field=models.DateTimeField(blank=True, help_text='When the runner began physical deletion.', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='delete_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspace',
            name='delete_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='delete_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspace',
            name='delete_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagebuildjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('active', 'Active'), ('failed', 'Failed'), ('deactivated', 'Deactivated'), ('pending_deletion', 'Pending Deletion'), ('deleting', 'Deleting'), ('deleted', 'Deleted'), ('delete_failed', 'Delete Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='imageinstance',
            name='status',
            field=models.CharField(choices=[('building', 'Building'), ('capturing', 'Capturing'), ('ready', 'Ready'), ('retired', 'Retired'), ('pending_deletion', 'Pending Deletion'), ('deleting', 'Deleting'), ('deleted', 'Deleted'), ('delete_failed', 'Delete Failed'), ('failed', 'Failed')], default='ready', help_text='Lifecycle status of the image instance.', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('create_workspace', 'Create Workspace'), ('update_workspace', 'Update Workspace'), ('run_prompt', 'Run Prompt'), ('cancel_session', 'Cancel Session'), ('stop_workspace', 'Stop Workspace'), ('resume_workspace', 'Resume Workspace'), ('remove_workspace', 'Remove Workspace'), ('start_terminal', 'Start Terminal'), ('start_desktop', 'Start Desktop'), ('stop_desktop', 'Stop Desktop'), ('create_image_artifact', 'Create Image Artifact'), ('delete_image', 'Delete Image'), ('create_workspace_from_image_artifact', 'Create Workspace From Image Artifact'), ('build_image', 'Build Image')], max_length=40),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='status',
            field=models.CharField(choices=[('creating', 'Creating'), ('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('pending_deletion', 'Pending Deletion'), ('deleting', 'Deleting'), ('deleted', 'Deleted'), ('delete_failed', 'Delete Failed'), ('removed', 'Removed')], default='creating', max_length=20),
        ),
    ]
