# Generated by Django 5.2.13 on 2026-04-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runners", "0009_merge_0008_and_0007_merge_0006"),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedefinition',
            name='delete_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagedefinition',
            name='delete_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagedefinition',
            name='delete_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='imagedefinition',
            name='delete_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagedefinition',
            name='delete_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='delete_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagedefinition',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('pending_deletion', 'Pending Deletion'), ('deleting', 'Deleting'), ('deleted', 'Deleted'), ('delete_failed', 'Delete Failed')], default='active', help_text='Lifecycle status of the image definition.', max_length=20),
        ),
    ]
