# Generated by Django 5.2.13 on 2026-09-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_credentialservice_target_path_and_more'),
        ('runners', '0010_imagedefinition_delete_attempt_count_and_more'),
        ('skills', '0002_delete_sessionskill'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentdefinition',
            name='unique_standard_agent_name',
        ),
        migrations.RemoveConstraint(
            model_name='agentdefinition',
            name='unique_org_agent_name',
        ),
        migrations.RemoveConstraint(
            model_name='agentcommand',
            name='unique_run_command_per_agent',
        ),
        migrations.RemoveConstraint(
            model_name='agentdefinitioncredentialrelation',
            name='unique_agent_credential_relation',
        ),
        migrations.RemoveConstraint(
            model_name='orgagentdefinitionactivation',
            name='unique_org_agent_activation',
        ),
        migrations.RemoveField(
            model_name='agentcredentialrelationcommand',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='agentdefinition',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='agentdefinition',
            name='required_credential_services',
        ),
        migrations.RemoveField(
            model_name='agentdefinitioncredentialrelation',
            name='agent_definition',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='agent_definition',
        ),
        migrations.RemoveField(
            model_name='orgagentdefinitionactivation',
            name='agent_definition',
        ),
        migrations.RemoveField(
            model_name='agentdefinitioncredentialrelation',
            name='credential_service',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='session',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='orgagentdefinitionactivation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='task',
            name='session',
        ),
        migrations.AlterField(
            model_name='imageinstance',
            name='credentials',
            field=models.ManyToManyField(blank=True, help_text='Credentials associated with this image instance. Workspace cloning must still supply credentials explicitly.', related_name='image_instances', to='credentials.credential'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('create_workspace', 'Create Workspace'), ('update_workspace', 'Update Workspace'), ('stop_workspace', 'Stop Workspace'), ('resume_workspace', 'Resume Workspace'), ('remove_workspace', 'Remove Workspace'), ('start_terminal', 'Start Terminal'), ('start_desktop', 'Start Desktop'), ('stop_desktop', 'Stop Desktop'), ('create_image_artifact', 'Create Image Artifact'), ('delete_image', 'Delete Image'), ('create_workspace_from_image_artifact', 'Create Workspace From Image Artifact'), ('build_image', 'Build Image')], max_length=40),
        ),
        migrations.DeleteModel(
            name='AgentCommand',
        ),
        migrations.DeleteModel(
            name='AgentCredentialRelationCommand',
        ),
        migrations.DeleteModel(
            name='AgentDefinition',
        ),
        migrations.DeleteModel(
            name='AgentDefinitionCredentialRelation',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='OrgAgentDefinitionActivation',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
