# Generated by Django 5.2.13 on 2026-05-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runners", "0010_imagedefinition_delete_attempt_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageinstance",
            name="is_organization_shared",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether this captured image is shared organization-wide. "
                    "Only org admins can toggle this."
                ),
            ),
        ),
    ]
