# Generated by Django 5.2.13 on 2026-09-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runners", "0011_remove_agentcredentialrelationcommand_relation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="credentials_present",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True if credential material is currently on the workspace disk. "
                    "Set after a successful inject; cleared only after a controlled stop "
                    "removes the secrets. External stops leave this true."
                ),
            ),
        ),
        migrations.RemoveField(
            model_name="imageinstance",
            name="credentials",
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("create_workspace", "Create Workspace"),
                    ("update_workspace", "Update Workspace"),
                    ("stop_workspace", "Stop Workspace"),
                    ("resume_workspace", "Resume Workspace"),
                    ("remove_workspace", "Remove Workspace"),
                    ("start_terminal", "Start Terminal"),
                    ("start_desktop", "Start Desktop"),
                    ("stop_desktop", "Stop Desktop"),
                    ("create_image_artifact", "Create Image Artifact"),
                    ("delete_image", "Delete Image"),
                    ("create_workspace_from_image_artifact", "Create Workspace From Image Artifact"),
                    ("build_image", "Build Image"),
                    ("inject_credentials", "Inject Credentials"),
                ],
                max_length=40,
            ),
        ),
    ]
