# Generated by Django 5.2.17 on 2026-09-06 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0013_workspace_desktop_geometry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('command', models.TextField(help_text='Shell command the process was started with.')),
                ('workdir', models.CharField(default='/workspace', max_length=1024)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('log_path', models.CharField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('running', 'Running'), ('exited', 'Exited'), ('killed', 'Killed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, help_text='Agent loop that started this process (informational, no FK).', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_processes', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace this process runs in. Deleting the workspace deletes its processes.', on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='runners.workspace')),
            ],
            options={
                'db_table': 'runners_workspace_process',
                'ordering': ['-started_at'],
            },
        ),
    ]
