# Generated by Django 5.2.17 on 2026-10-02 22:07

import hashlib
import json
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

RECIPE_FIELDS = (
    "runtime_type",
    "base_distro",
    "packages",
    "env_vars",
    "custom_dockerfile",
    "custom_init_script",
)


def clean_task_references(apps, schema_editor):
    Definition = apps.get_model("runners", "ImageDefinition")
    Definition.objects.filter(status="active", is_active=False).update(
        status="deactivated"
    )
    Task = apps.get_model("runners", "Task")
    for model_name, fields in [
        ("ImageInstance", ["creating_task_id", "deleting_task_id"]),
        ("ImageBuildJob", ["deleting_task_id"]),
    ]:
        Model = apps.get_model("runners", model_name)
        for row in Model.objects.all():
            for field in fields:
                value = getattr(row, field)
                if value is None:
                    continue
                try:
                    task_id = uuid.UUID(value)
                except ValueError:
                    task_id = None
                if task_id and Task.objects.filter(id=task_id).exists():
                    setattr(row, field, task_id.hex)
                    continue
                # Preserve uninterpretable correlation without inventing a Task.
                metadata = dict(row.legacy_task_references or {})
                metadata[field] = value
                row.legacy_task_references = metadata
                setattr(row, field, None)
            row.save()


def flush_deferred_constraints(apps, schema_editor):
    # Data updates can enqueue deferred FK triggers on PostgreSQL. Drain them
    # before subsequent DDL, without giving up this migration's atomicity.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")
        schema_editor.execute("SET CONSTRAINTS ALL DEFERRED")


def seed_revisions(apps, schema_editor):
    Definition = apps.get_model("runners", "ImageDefinition")
    Revision = apps.get_model("runners", "ImageRevision")
    Image = apps.get_model("runners", "ImageInstance")
    Job = apps.get_model("runners", "ImageBuildJob")
    for definition in Definition.objects.all():
        recipe = {field: getattr(definition, field) for field in RECIPE_FIELDS}
        digest = hashlib.sha256(json.dumps(recipe, sort_keys=True).encode()).hexdigest()
        Revision.objects.create(
            definition_id=definition.id,
            recipe=recipe,
            digest=digest,
            rendered_input=None,
        )
    # Today's recipe does NOT prove the recipe of an overwritten legacy build.
    Image.objects.all().update(is_legacy=True)
    Image.objects.filter(size_bytes__lte=0).update(size_bytes=None)
    for image in Image.objects.exclude(build_job_id=None):
        Job.objects.filter(id=image.build_job_id).update(
            current_generation_id=image.id
            if image.status in ("ready", "retired")
            else None,
            pending_generation_id=image.id if image.status == "building" else None,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("runners", "0016_workspaceprocess_kind_temp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="imageinstance",
            name="legacy_task_references",
            field=models.JSONField(default=dict, blank=True),
        ),
        migrations.AddField(
            model_name="imagebuildjob",
            name="legacy_task_references",
            field=models.JSONField(default=dict, blank=True),
        ),
        migrations.RunPython(clean_task_references, migrations.RunPython.noop),
        migrations.RunPython(flush_deferred_constraints, migrations.RunPython.noop),
        # Remove string indexes (including PostgreSQL varchar_pattern_ops)
        # before the UUID cast. ForeignKey restores ordinary UUID indexes.
        migrations.AlterField(
            model_name="imagebuildjob",
            name="deleting_task_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="imageinstance",
            name="creating_task_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="imageinstance",
            name="deleting_task_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RemoveField(
            model_name="imagedefinition",
            name="is_active",
        ),
        migrations.AddField(
            model_name="imagebuildjob",
            name="current_generation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_assignments",
                to="runners.imageinstance",
            ),
        ),
        migrations.RenameField(
            model_name="imagebuildjob",
            old_name="deleting_task_id",
            new_name="deleting_task",
        ),
        migrations.AlterField(
            model_name="imagebuildjob",
            name="deleting_task",
            field=models.ForeignKey(
                blank=True,
                db_column="deleting_task_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="runners.task",
            ),
        ),
        migrations.AddField(
            model_name="imagebuildjob",
            name="pending_generation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pending_assignments",
                to="runners.imageinstance",
            ),
        ),
        migrations.RenameField(
            model_name="imageinstance",
            old_name="creating_task_id",
            new_name="creating_task",
        ),
        migrations.AlterField(
            model_name="imageinstance",
            name="creating_task",
            field=models.ForeignKey(
                blank=True,
                db_column="creating_task_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="runners.task",
            ),
        ),
        migrations.RenameField(
            model_name="imageinstance",
            old_name="deleting_task_id",
            new_name="deleting_task",
        ),
        migrations.AlterField(
            model_name="imageinstance",
            name="deleting_task",
            field=models.ForeignKey(
                blank=True,
                db_column="deleting_task_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="runners.task",
            ),
        ),
        migrations.AddField(
            model_name="imageinstance",
            name="generation",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageinstance",
            name="is_legacy",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="imageinstance",
            name="build_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generations",
                to="runners.imagebuildjob",
            ),
        ),
        migrations.AlterField(
            model_name="imageinstance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this image instance.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="image_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="imageinstance",
            name="size_bytes",
            field=models.BigIntegerField(
                blank=True,
                default=None,
                help_text="Image instance size in bytes.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ImageRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("digest", models.CharField(max_length=64)),
                ("recipe", models.JSONField()),
                ("rendered_input", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="runners.imagedefinition",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="imageinstance",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generations",
                to="runners.imagerevision",
            ),
        ),
        migrations.RunPython(seed_revisions, migrations.RunPython.noop),
        migrations.RunPython(flush_deferred_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="imageinstance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("size_bytes__isnull", True),
                    ("size_bytes__gte", 0),
                    _connector="OR",
                ),
                name="image_size_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="imageinstance",
            constraint=models.UniqueConstraint(
                fields=("build_job", "generation"), name="unique_image_generation"
            ),
        ),
        migrations.AddConstraint(
            model_name="imageinstance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_legacy", True),
                    models.Q(
                        ("build_job__isnull", False),
                        ("generation__gte", 1),
                        ("generation__isnull", False),
                        ("origin_definition__isnull", False),
                        ("origin_type", "definition_build"),
                        ("origin_workspace__isnull", True),
                        ("revision__isnull", False),
                    ),
                    models.Q(
                        ("build_job__isnull", True),
                        ("generation__isnull", True),
                        ("origin_definition__isnull", True),
                        ("origin_type", "workspace_capture"),
                        ("revision__isnull", True),
                        ("runtime_type", "qemu"),
                    ),
                    _connector="OR",
                ),
                name="image_origin_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="imagerevision",
            constraint=models.UniqueConstraint(
                fields=("definition", "digest"), name="unique_image_revision_digest"
            ),
        ),
    ]
