# Generated by Django 5.2.17 on 2026-10-02 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_intents(apps, schema_editor):
    from datetime import timedelta

    Task = apps.get_model("runners", "Task")
    Command = apps.get_model("runners", "LifecycleCommand")
    Workspace = apps.get_model("runners", "Workspace")
    now = django.utils.timezone.now()
    types = {
        "create_workspace",
        "create_workspace_from_image_artifact",
        "stop_workspace",
        "resume_workspace",
        "update_workspace",
        "remove_workspace",
        "build_image",
        "create_image_artifact",
        "delete_image",
    }
    for task in Task.objects.filter(
        type__in=types, status__in=["pending", "in_progress"]
    ).order_by("created_at"):
        Command.objects.create(task=task, deadline_at=now + timedelta(hours=2))
        if task.workspace_id:
            Workspace.objects.filter(pk=task.workspace_id).update(
                current_task_id=task.id
            )


class Migration(migrations.Migration):
    dependencies = [
        ("runners", "0017_immutable_image_generations"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifecycleCommand",
            fields=[
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="runners.task",
                    ),
                ),
                ("event", models.CharField(blank=True, max_length=80)),
                ("payload", models.JSONField(default=dict)),
                ("target", models.CharField(blank=True, max_length=512)),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("deliveries", models.PositiveIntegerField(default=0)),
                ("phase", models.CharField(default="intent", max_length=40)),
                ("heartbeat_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deadline_at", models.DateTimeField()),
                (
                    "next_delivery_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "lease_until",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workspace",
            name="current_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_workspaces",
                to="runners.task",
            ),
        ),
        migrations.RunPython(seed_intents, migrations.RunPython.noop),
    ]
