# Generated by Django 5.2.17 on 2026-10-03 00:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0018_lifecyclecommand_workspace_current_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime_type', models.CharField(max_length=20)),
                ('collected_at', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('errors', models.JSONField(default=list)),
                ('filesystems', models.JSONField(default=list)),
                ('foreign_resource_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_id', models.TextField()),
                ('kind', models.CharField(max_length=40)),
                ('managed', models.BooleanField(default=False)),
                ('state', models.CharField(default='unknown', max_length=40)),
                ('allocated_bytes', models.PositiveBigIntegerField(null=True)),
                ('logical_bytes', models.PositiveBigIntegerField(null=True)),
                ('virtual_bytes', models.PositiveBigIntegerField(null=True)),
                ('shared_bytes', models.PositiveBigIntegerField(null=True)),
                ('reclaimable_bytes', models.PositiveBigIntegerField(null=True)),
                ('provenance', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='runners.imageinstance')),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='runners.workspace')),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='runners.inventoryruntime')),
            ],
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255)),
                ('epoch', models.UUIDField()),
                ('sequence', models.PositiveBigIntegerField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('complete', models.BooleanField(default=False)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runners.runner')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryruntime',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtimes', to='runners.inventorysnapshot'),
        ),
        migrations.CreateModel(
            name='InventoryEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='runners.inventoryresource')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='runners.inventoryresource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='inventory_unique_edge')],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='runners.inventoryresource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resource', 'reference'), name='inventory_unique_alias')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryresource',
            constraint=models.UniqueConstraint(fields=('runtime', 'physical_id'), name='inventory_unique_resource'),
        ),
        migrations.AddConstraint(
            model_name='inventorysnapshot',
            constraint=models.UniqueConstraint(fields=('runner', 'session', 'epoch', 'sequence'), name='inventory_unique_sequence'),
        ),
        migrations.AddConstraint(
            model_name='inventoryruntime',
            constraint=models.UniqueConstraint(fields=('snapshot', 'runtime_type'), name='inventory_unique_runtime'),
        ),
    ]
