# Generated by Django 5.2.17 on 2026-10-03 00:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0019_inventoryruntime_inventoryresource_inventorysnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRefresh',
            fields=[
                ('runner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='runners.runner')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_delivery_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fulfilled_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
