# Generated by Django 5.2.17 on 2026-10-03 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0020_inventoryrefresh'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(default='stop', max_length=32)),
                ('prior_running', models.BooleanField(default=False)),
                ('resume_suppressed', models.BooleanField(default=False)),
                ('diagnostic', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='runners.task')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='runners.imageinstance')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runners.workspace')),
            ],
        ),
    ]
