# Generated by Django 5.2.17 on 2026-10-03 01:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("runners", "0021_capturerequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageDeletionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_type", models.CharField(max_length=20)),
                ("target_id", models.UUIDField()),
                ("mode", models.CharField(default="deferred", max_length=12)),
                ("phase", models.CharField(default="waiting_inventory", max_length=32)),
                ("diagnostic", models.TextField(blank=True)),
                ("fingerprint", models.CharField(blank=True, max_length=64)),
                ("approval", models.JSONField(default=dict)),
                ("previous", models.JSONField(default=dict)),
                ("children", models.JSONField(default=dict)),
                ("released_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("phase__in", ["completed", "cancelled"]), _negated=True
                        ),
                        fields=("organization", "target_type", "target_id"),
                        name="unique_live_image_deletion",
                    )
                ],
            },
        ),
    ]
