# Generated by Django 5.2.13 on 2026-10-05 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_versioned_images'),
        ('runners', '0023_preserve_delete_intents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_deletion', 'Pending Deletion'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'runners_captured_image',
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceRecreateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('reset', 'Reset'), ('update', 'Update'), ('capture', 'Capture')], max_length=16)),
                ('phase', models.CharField(default='remove', max_length=16)),
                ('final_running', models.BooleanField(default=True)),
                ('diagnostic', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'runners_workspace_recreate_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='imageinstance',
            name='image_origin_valid',
        ),
        migrations.AddField(
            model_name='imageinstance',
            name='message',
            field=models.TextField(blank=True, db_default='', default='', help_text='Short description of what changed in this version.'),
        ),
        migrations.AddField(
            model_name='imageinstance',
            name='min_disk_size_gb',
            field=models.PositiveIntegerField(blank=True, help_text='Smallest workspace disk (GiB) that can hold this captured version.', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='pending_base_image_instance',
            field=models.ForeignKey(blank=True, help_text='Target image version of an in-flight or failed recreate. It pins the version until the workspace has been provisioned from it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_workspaces', to='runners.imageinstance'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='repos',
            field=models.JSONField(blank=True, db_default=models.Value([], output_field=models.JSONField()), default=list, help_text='Repositories cloned on top of the base image when provisioning.'),
        ),
        migrations.AlterField(
            model_name='imageinstance',
            name='generation',
            field=models.PositiveIntegerField(blank=True, help_text='Version number within the image line (build job or capture).', null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='active_operation',
            field=models.CharField(blank=True, choices=[('creating', 'Creating'), ('starting', 'Starting'), ('stopping', 'Stopping'), ('restarting', 'Restarting'), ('removing', 'Removing'), ('capturing_image', 'Capturing Image'), ('resetting', 'Resetting'), ('updating', 'Updating')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='capturedimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capturedimage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_images', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='capturedimage',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_images', to='runners.runner'),
        ),
        migrations.AddField(
            model_name='imageinstance',
            name='captured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='runners.capturedimage'),
        ),
        migrations.AddField(
            model_name='workspacerecreaterequest',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='runners.task'),
        ),
        migrations.AddField(
            model_name='workspacerecreaterequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacerecreaterequest',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recreate_requests', to='runners.workspace'),
        ),
    ]
